Aging penalty fix
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #1118
Opened 2023-04-12 05:17 UTC by sumankun

## Changelog:
- removed vanilla mortality system, so all became immortal (in `00_defines.txt` file)
- instead of vanilla system we have `character modifiers`, which reduce `health`/`prowess`
- It uses equivalent human age. We apply modifier after >= 30(human) years old. It is updated on every birthday. There are 365 days, and each character has it own birthday, so it doesnt touch performance
- we have two variations of that penalty. One with prowess, one without prowess. It depends on `dynasty legacy` (which removes prowess reduction)
- removed `game start health` bonus, i believe it was used to make them live longer
<details>
<summary>Looks like this</summary>

![image](https://user-images.githubusercontent.com/84410981/231363037-dd8a0b26-52bd-4520-aae3-e067668287cc.png)
![image](https://user-images.githubusercontent.com/84410981/231673803-689c9049-45a5-4dda-aaa3-6f99519b480b.png)

</details>

## Data for health penalty calculation:
I wrote vanilla numbers in excel to calculate how fast it reduces health/prowess with vanilla mortality system. Use `10.0 health` and `100 prowess` as starting numbers.
<details>
<summary>Age 25-80</summary>

![image](https://user-images.githubusercontent.com/84410981/231354363-352f36c3-11b1-4c2a-8f7d-39d1eba00e79.png)
</details>
<details>
<summary>Age 80-120</summary>

![image](https://user-images.githubusercontent.com/84410981/231384154-2ef9f7be-3bd3-4af8-a0b4-533698ed4064.png)
</details>

- I increased prowess losing chance number a little bit, because vanilla uses preudorandom
- In `modifier file` i added to every modifier comments like `#+0.2`. It means i make health penalty bigger from above excel table by this amount. It is required because game thinks it is illness, so it adds health resistance bonus when detect modifier.

## To-do-list:
- [x] Balance aging penalties, so humanity dies like in vanilla (health resistance bonus is main enemy)
## Tests:
- [x] There are no errors in `changed files` in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log`

# How to test:
1. Start up version `1.8.2` of **Crusader Kings III** and look for human characters using _observer mode_.
2. If human dies as intended, you can check other races too, but they should be ok as long as human race is ok.

2023-04-14 12:39 UTC, ElMariuso approved these changes
Everything looks ok, I'm not sure because it's a big change to how Vanilla works, so I think more reviewers are needed.

2023-04-16 07:53 UTC, ercarp approved these changes
Observed a game for about 200 years and everything looks good to me. The modifier is correctly applied to all characters when they reach a human equivalent age of 30 and characters seem to be dying of old age between the ages of 60-75 for the most part; I did observe some dying a bit sooner, but not many. The median seems to be around 75 from what I can tell.

However, aside from Duke Newall of Balor (died at 95) and Count Panoramix of Blackwald (died at 88), I don't think I saw a single new human character age past 80, which could be seen as a "problem". I personally feel like humans would be more likely to grow past 80 in the Warcraft universe where you have access to priests, druids, and paladins with healing magic - however, that might be better suited for a different PR.

For now, I would say this work as intended and I can't personally see any problems with the implementation. It's nice that elves aren't dying randomly in their 70s anymore. LGTM!

2023-04-16 16:39 UTC, zumbak04 requested changes

2023-04-16 16:39 UTC, zumbak04 commented on common/modifiers/wc_age_penalty_modifiers.txt
> +﻿30_age_penalty = {
Ooof, that's many modifiers. Why you didn't use `stacking = yes` modifier?

2023-04-16 16:39 UTC, zumbak04 commented on common/on_action/wc_aging_penalties.txt
> +				has_trait_with_flag = can_not_get_sick
Check `is_immortal`.

2023-04-16 16:39 UTC, zumbak04 commented on common/on_action/wc_aging_penalties.txt
> +				has_trait_with_flag = can_not_get_sick
I would add a new trait flag with its own description. This way you won't need the trait limits below.

2023-04-16 16:39 UTC, zumbak04 commented on common/on_action/wc_aging_penalties.txt
> +			if = {
If you implement `stacking = yes` on the modifier, you can replace this else/if logic with a math formula. The input of the formula should be your age, the output should be "stacks" of the modifier.

2023-04-16 17:05 UTC, zumbak04 commented on common/on_action/wc_aging_penalties.txt
> +				name = my_human_age_multiplier
Not sure why it's called `my_human_age_multiplier`. It gets the mutiplayer for all the races, not only humans.

2023-04-17 09:38 UTC, zumbak04 requested changes

2023-04-17 09:38 UTC, zumbak04 commented on common/on_action/wc_aging_penalties.txt
> +					aging_trigger_between = { AGE_1 = 35 AGE_2 = 40 }
Optimization.
If the effect fires, you're 35-40 years old, but do have the penalty modifier. This returns false and you go all the way down else/if chain.

Solution:
You split `aging_trigger_between` in 2 triggers: `has_aging_penalty_trigger = { AGE }` and `race_relative_age_between_trigger = { AGE_1 AGE_2 }`. First you check `race_relative_age_between_trigger`. If true, you check `has_aging_penalty_trigger`. If false, you get the modifier.

2023-04-17 09:38 UTC, zumbak04 commented on common/scripted_effects/wc_age_effects.txt
> +clear_age_penalties = {
The effect names should end with `_effect`.

2023-04-17 09:38 UTC, zumbak04 commented on common/scripted_triggers/wc_age_triggers.txt
> +aging_trigger_between = {
The trigger names should end with `_trigger`

2023-04-17 09:38 UTC, zumbak04 commented on common/traits/wc_infusion_traits.txt
> +	flag = no_aging_penalties
Add a localization.

2023-04-17 09:38 UTC, zumbak04 commented on common/modifiers/wc_age_penalty_modifiers.txt
> +﻿30_age_penalty = {
The modifier names should end with `_modifier`.

2023-04-17 14:23 UTC, zumbak04 approved these changes
LGTM! But left one comment to address.

2023-04-17 14:23 UTC, zumbak04 commented on localization/english/triggers/wc_character_triggers_l_english.yml
> + has_trait_with_flag_no_aging_penalties_global:0 "Is #bold not#! aging"
I meant `TRAIT_FLAG_DESC_<flag name>` localization, but this is nice too. Keep it.

2023-04-17 14:42 UTC, merged