Religions update
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #1214
Opened 2023-09-11 13:22 UTC by Grekopithikos

## Changelog:
- Added a doctrine version of Eastern Syncretism, now named Eastern Conclave, replacing the tenet for the faiths that had it.
- Added icons for the Eastern Conclave doctrine and tenet
- Changed the tenets of many faiths
  - Ragnarism now has the by Any Means Necessary doctrine, and the Sacred Lies, Struggle and Submission and Cthonic Redoubts(Localized as Volcanic Veneration) tenets
  - Void Religion is now equal gender and plural
  - Forgotten Shadow has the Literalism, Struggle and Submission and Monasticism tenets.
  - Holy Light has the unrelenting tenet
  - Secularism has the Communal Identity tenet
  - Tirassian has the Astrology tenet
  - Khazism has the Cthonic Redoubts tenet
  - Gwyari has the Ancestor Worship tenet
  - Belorism has the Esotericism tenet
- More custom icons from vanilla are available for creating a new faith

## Developer changelog:
- Added this thing.
- Changed that thing.

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:

2023-09-12 19:26 UTC, ElMariuso approved these changes
I reviewed it on the surface, and I followed the evolution a little (since we have a dedicated channel).
But LGTM

2023-09-13 10:07 UTC, sumankun requested changes
1) Need to remove non-english localizations
2) tenet icons are wrong dds formats, will fix them myself

2023-09-13 10:16 UTC, Grekopithikos commented on common/religion/religions/void_group.txt
> -			doctrine = tenet_eastern_kingdoms_syncretism
I removed it because I didn't think it would make sense for the Forsaken to have friendly relations with the rest of the Alliance countries

2023-09-14 16:17 UTC, arithon approved these changes
loc LGTM

2023-09-14 16:19 UTC, sumankun approved these changes
lgtm

2023-09-14 16:22 UTC, merged