Goblin Loan Mechanic
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #1228
Opened 2023-10-02 20:01 UTC by sumankun

This is the Goblins Loans system. As far as i checked there are no errors in `error.log`
## Changelog:
- Decision for borrowing/paying back `loan`. 
- `Fortunistic` faith has a head of faith, which funtions as bank and called `Fortunistic Reserve System`. All loans are taken and go back to this title. (discussed with Mariuso). Rulers of this title has titlename `Banker`.
- Due to vanilla character interaction `ask gold from head of faith`, this bank can help for all Fortunistic rulers.
- You return the debt paying 4 times (1/4)+25% on top of it. It asks to return 1/4 of debt every 5 years, the first pay out can take a little longer.
- `FRS holder` has `modifier` +10 gold per month

<details>
<summary>Daelin took debt, first pay back</summary>

![image](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/84410981/03b59d5f-d4a7-4f0a-a018-1276f836b816)
</details>
<details>
<summary>There are three options</summary>

![image](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/84410981/f81a9b56-3cb4-4145-b4ef-88c59b4ab048)
![image](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/84410981/bb494e0b-3e8e-4342-9831-8281461c3ef7)
![image](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/84410981/238f911b-e73b-4371-be42-b90ecbcccabf)
</details>
<details>
<summary>Son successfully inherited the loan</summary>

![image](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/assets/84410981/1a8c15b0-6b2a-469c-923d-2330f224a440)
</details>

## Tests:
- [x] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log`

# How to test:
- There is minor decision to take loan from goblins
- Periodically (usually 5 years) They ask to return 1/4 debt +25% on top. Or you can pay back though decision
- If you die, your heir inherit the loan

2023-10-02 20:31 UTC, ElMariuso commented
> You made a new character for the title? Wouldn't it make more sense for the Steamwheedle Trade Prince to be the head of faith?

No?

2023-10-02 20:33 UTC, Grekopithikos commented
hmm ok nevermind then

2023-10-03 14:50 UTC, Gaben1025 approved these changes
Amazing work, no errors in log,this is exactly what I had in mind LGTM!

2023-10-03 20:29 UTC, arithon requested changes
just minor things, good in general.

2023-10-03 20:29 UTC, arithon commented on localization/english/wc_decisions_l_english.yml
> + borrow_loan_goblin_decision_desc:0 "One can only hope that this won't be too complicated of a process, but the Goblins aren't exactly known for making matters too easy for folks who want them to thr
I'd go here with "and hope that when the time comes", but I think it's ok like this, too.

2023-10-03 20:29 UTC, arithon commented on localization/english/wc_decisions_l_english.yml
> + repay_loan_goblin_decision_tooltip:0 "To have a debt hanging over me is unbecoming of a [ROOT.Char.GetTitleAsNameNoTooltip] – the time has come to repay the money I owe"
Shouldn't this end with a . ?

2023-10-03 20:29 UTC, arithon commented on localization/english/wc_decisions_l_english.yml
> + repay_loan_goblin_decision_desc:0 "You #V will pay#! a #P quarter#! of the initial debt and #N 25%#! on top\n\nIt is high time these lands were eased of their burdens, and what greater burden is the
```suggestion
 repay_loan_goblin_decision_desc:0 "You #V will pay#! a #P quarter#! of the initial debt and #N 25%#! on top\n\nIt is high time these lands were eased of their burdens, and what greater burden is there on any land than to be financially dependent on external forces that seek to scrounge off it? Indeed, the time has come, and the wealth that the Goblins have provided in the past shall now be returned in plenty."
```

2023-10-03 20:35 UTC, sumankun commented on localization/english/wc_decisions_l_english.yml
> + repay_loan_goblin_decision_tooltip:0 "To have a debt hanging over me is unbecoming of a [ROOT.Char.GetTitleAsNameNoTooltip] – the time has come to repay the money I owe"
> Shouldn't this end with a . ?

Tooltips and confirms without dots

2023-10-03 20:42 UTC, arithon approved these changes
LGTM

2023-10-03 20:43 UTC, merged