Secret faiths
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #1369
Opened 2024-02-21 18:36 UTC by Grekopithikos

## Changelog:
- Replaced every instance of the commented out `secret_religion=[insert faith]` with `effect = { make_character_crypto_religionist_effect = { CRYPTO_RELIGION = faith:[insert faith] } }` so that they could properly have secret faiths

## Developer changelog:
- Added this thing.
- Changed that thing.

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
Check if the characters have the related secrets. I think observer mode shows them?
And if there are any characters with no secret faith that should have one or the reverse let me know.

2024-02-21 20:52 UTC, edmund-h submitted a review, later dismissed
hey i just pushed some changes. since you do a lot of work to maintain the character histories, would you mind following the spacing i did there for characters who have multiple traits and/or effects plus the crypto religionist effect? i know the convention is to keep traits on the same line, but adding these effects on the same line is a little too much. otherwise looks good.

2024-02-22 18:05 UTC, Grekopithikos commented
I'll try

2024-02-23 16:41 UTC, ElMariuso requested changes
Change requested

2024-02-23 16:41 UTC, ElMariuso commented on history/characters/310000_patron_characters.txt
> +			make_character_crypto_religionist_effect = { CRYPTO_RELIGION = faith:forgotten_shadow
Missing bracket here

2024-02-23 17:12 UTC, ElMariuso approved these changes
LGTM. Everything work fine in game too

2024-02-23 17:21 UTC, merged