Genocide
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #1386
Opened 2024-04-24 13:25 UTC by robmart

## Changelog:
- Added Purge Population councillor task
  - Changes county culture and faith to the liege's
  - Gives rulers of the genocided culture and faith the Avenge Genocide casus belli
  - Makes people really angry at you and massively lowers development
  
- Added Cleanse County councillor task
  - Same as purge, but it removes corruption modifiers and is faster
  
- Added Corrupt County councillor task
  - Variant of Purge Population available to characters with a high affinity to a specific magic (mostly those with being traits)
  - Adds a corruption modifier to a county, giving bonuses to rulers with affinity for that magic, and maluses to rulers without affinity

- Added Avenge Genocide casus belli
  - Added to rulers of a genocided culture or faith
  - Conquers the genocided counties 

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
- Check that all three task types work correctly
- Check that the correct people have access to the correct task type
- Check that the casus belli works correctly
- At game start the counties that have a culture/faith heavily related to a type of corruption will have that corruption modifier added to it. Check that the right counties have the right modifiers, ie LK has death corruption, old god cultists have void corruption, etc.

2024-09-06 05:35 UTC, Rimaka94 commented
## Test Criteria
:white_check_mark: Check that all three task types work correctly
:white_check_mark: Check that the correct people have access to the correct task type
:white_check_mark: Check that the casus belli works correctly
:white_check_mark: At game start the counties that have a culture/faith heavily related to a type of corruption will have that corruption modifier added to it. Check that the right counties have the right modifiers, ie LK has death corruption, old god cultists have void corruption, etc.

_All of the primary mechanics listed on the 'How to test' section are working as intended from my playtests. I go into specifics in the tests below, including some issues linked to these mechanics. I haven't listed every single test case, as I often jump around to different characters/dates._

## Test 1 - Frostwolf Clan RoC
### Ancestral / Frostwolf

- :white_check_mark: Purge Population is used.
- :white_check_mark: Holy Light/Alteraci ruler properly received Avenge Genocide Casus Belli.
  - :white_check_mark: Winning this war properly gives back the purged title.
- :x: **Purge Population** tooltip in Council states every Minority vassal loses 50 Opinion (Disapproves Genocide). The event itself is a -25 Opinion Loss (Disapproves of Genocide). Possibly remove this line from the Council button tooltip due to the fact that you could get different results depending on if you're purging or cleansing? See SCREENSHOT 1.

<details>
<summary>SCREENSHOT 1</summary>

![image](https://github.com/user-attachments/assets/257a5c9d-0f3d-41e1-bde3-04c558119ebb)
</details>

- :white_check_mark: Cleanse County is properly used vs Corruptism county. Determined by comparing speed of the task (it is quicker) and the final event (The Cleansing vs The Purging).
  - :large_orange_diamond: There is no indication that you are Cleansing until the event shows at competion, is this intended? (I would assume yes, as I wouldn't think there's a way to make Purge Population dynamically shift between Cleanse and Purge depending on the county you are hovering over)
  - :white_check_mark: Properly removes corruption from county.
  - :white_check_mark: Faster than Purge.
- :x: The following event options need punctuation:
  - genocide_task.2001.a:0 "The deed is done"
  - genocide_task.2101.a:0 "The foul corruption has been defeated"
  - genocide_task.2201.a:0 "A job well done"
  - genocide_task.2201.a.holder:0 "Leave them be"
  - genocide_task.2201.b:0 "This land does not belong to them"
  - genocide_task.2201.c:0 "They shall go the way of their subjects"
- :white_check_mark: Opinion losses from Culture/Religion you are purging/cleansing and severe development/control penalties are properly applied alongside the negative county modifier.
- :x: **genocide_task.0401** option A's tooltip localization is incomplete, see SCREENSHOT 2. `genocide_task.0401.a.progress:0 "The progress of the Cleansing in [county.GetName]"`
<details>
<summary>SCREENSHOT 2</summary>

![image](https://github.com/user-attachments/assets/6d1de931-6ce6-40a8-9cb2-9e602391c972)
</details>

- :x: **genocide_task.0502.desc**  final sentence has two periods rather than an ellipsis or a single period. Should likely be "All that remains is the decision of where to invest these resources..."

## Test 2 - Uplands RoC
### Corruptic / Blackrock
- :white_check_mark: Corrupt County is used.
  - :white_check_mark: Fel Corruption is properly added to County.
  - :white_check_mark: Corrupt County (Fel) works fine when corrupting a county of same faith, but different culture.
- :white_check_mark: Corrupt County (Fel) vs a county of another corruption (Death) properly removes old corruption and adds your corruption, and vice versa. Tested Shadow as well.
- :x: **genocide_task.0302** title localization needs to be corrected, see SCREENSHOT 3. `genocide_task.0302.t:0 "Fuel for a [councillor_liege.GetFaith.PantheonTerm]"`
<details>
<summary>SCREENSHOT 3</summary>

![image](https://github.com/user-attachments/assets/85ea1a7a-cc37-4423-8e9e-1011ba55da45)
</details>

2024-09-16 07:21 UTC, helloruhe commented
Quick Test

1. Corrupted Plague modifier needs punctuation
![image](https://github.com/user-attachments/assets/0bde7601-a2ea-4da6-aba8-c2783fb0270e)
2. Why would minority disapprove of genocide if it's going to their own religion or culture? Does it have to be both?
![image](https://github.com/user-attachments/assets/0f0779bb-a6a3-422f-9d6b-9f6030f7a0fb)

2024-09-17 09:59 UTC, helloruhe approved these changes
whatever you say beautiful

2024-09-20 11:28 UTC, helloruhe commented on common/council_tasks/wc_genocide_councilor_tasks.txt
> +		}
does it make sense for them to disapprove of it if their culture/religion isnt affected?

2024-09-20 11:30 UTC, helloruhe commented on common/modifiers/wc_genocide_modifiers.txt
> +	epidemic_resistance = 5
supposed to be negative?
```suggestion
	epidemic_resistance = -5
```

2024-09-20 11:31 UTC, helloruhe commented on common/modifiers/wc_genocide_modifiers.txt
> +	epidemic_resistance = 15
```suggestion
	epidemic_resistance = -15
```

2024-09-20 11:31 UTC, helloruhe commented on common/modifiers/wc_genocide_modifiers.txt
> +	epidemic_resistance = 25
```suggestion
	epidemic_resistance = -25
```

2024-09-20 11:33 UTC, helloruhe commented on common/on_action/game_start.txt
> +		}
why are we saving this scope if corrupt_county_effect uses a parameter for it? i don't see scope:on_start mentioned anywhere else

2024-09-20 11:35 UTC, helloruhe commented on common/on_action/wc_genocide_on_actions.txt
> +        250 = 0
?

2024-09-20 11:39 UTC, helloruhe commented on common/scripted_effects/wc_genocide_effects.txt
> +    }
can we do this in a switch instead?

2024-09-20 11:41 UTC, helloruhe commented on common/scripted_triggers/wc_genocide_triggers.txt
> +# Don't crucify me please
jaja

2024-09-20 11:42 UTC, helloruhe commented on common/scripted_triggers/wc_religious_triggers.txt
>  	}
what bro

2024-09-20 11:46 UTC, helloruhe commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
```suggestion
        stress_impact = {
            zealous = major_stress_impact_loss
            sadistic = major_stress_impact_loss
            arbitrary = major_stress_impact_loss
            callous = major_stress_impact_loss

            forgiving = major_stress_impact_gain
            just = major_stress_impact_gain
            generous = major_stress_impact_gain
            compassionate = major_stress_impact_gain
        }
```

2024-09-20 11:47 UTC, helloruhe commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
try not to use raw values
```suggestion
        stress_impact = {
            paranoid = minor_stress_impact_gain
        }
```

2024-09-20 11:48 UTC, helloruhe commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
again, raw values r not good (usually)
```suggestion
        stress_impact = {
            forgiving = minor_stress_impact_gain
            just = minor_stress_impact_gain
            generous = minor_stress_impact_gain
            compassionate = minor_stress_impact_gain
            sadistic = minor_stress_impact_loss
            arbitrary = minor_stress_impact_loss
            callous = minor_stress_impact_loss
            wrathful = minor_stress_impact_loss
            vengeful = minor_stress_impact_loss
        }
```

2024-09-20 11:49 UTC, helloruhe commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
```suggestion
        stress_impact = {
            paranoid = minor_stress_impact_gain
            ambitious = minor_stress_impact_gain
            wrathful = minor_stress_impact_gain
            vengeful = minor_stress_impact_gain
        }
```

2024-09-20 11:51 UTC, helloruhe commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
```suggestion
        stress_impact = {
            brave = minor_stress_impact_loss
            wrathful = medium_stress_impact_loss
            craven = medium_stress_impact_gain
        }
```

2024-09-20 11:52 UTC, helloruhe commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
```suggestion
        stress_impact = {
            brave = minor_stress_impact_gain
            wrathful = medium_stress_impact_gain
            craven = medium_stress_impact_loss
        }
```

2024-09-20 11:53 UTC, helloruhe commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
you get the idea, not gonna comment on any more of these
```suggestion
        stress_impact = {
            compassionate = minor_stress_impact_loss
            arrogant = minor_stress_impact_gain
            sadistic = medium_stress_impact_gain
        }
```

2024-09-20 11:54 UTC, helloruhe commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
```suggestion
        stress_impact = {
            forgiving = major_stress_impact_gain
            just = major_stress_impact_gain
            generous = major_stress_impact_gain
            compassionate = major_stress_impact_gain
        }
```

2024-09-20 11:54 UTC, helloruhe commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
```suggestion
        stress_impact = {
            zealous = minor_stress_impact_gain
            sadistic = minor_stress_impact_gain
            callous = minor_stress_impact_gain
        }
```

2024-09-20 11:55 UTC, helloruhe commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
```suggestion
        stress_impact = {
            forgiving = major_stress_impact_gain
            just = major_stress_impact_gain
            generous = major_stress_impact_gain
            compassionate = major_stress_impact_gain
        }
```

2024-09-20 11:56 UTC, helloruhe commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
```suggestion
        stress_impact = {
            zealous = minor_stress_impact_gain
            sadistic = minor_stress_impact_gain
            callous = minor_stress_impact_gain
            just = minor_stress_impact_loss
            generous = minor_stress_impact_loss
        }
```

2024-09-20 11:56 UTC, helloruhe commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
ok you get the idea for this too, not commenting on any more of these
```suggestion
        stress_impact = {
            zealous = minor_stress_impact_loss
            sadistic = minor_stress_loss
            forgiving = medium_stress_impact_gain
            just = minor_stress_impact_gain
            generous = medium_stress_impact_gain
            compassionate = major_stress_impact_gain
        }
```

2024-09-20 11:57 UTC, helloruhe commented on events/councillor_task_events/wc_genocide_task_events.txt
> +    }
looks a little weird when they both have the same animation

2024-09-20 11:58 UTC, helloruhe requested changes
since we're using the conversion speed game rule to also affect genocide, it would be wise to note that in the conversion speed game rule text

2024-09-20 12:04 UTC, helloruhe commented on localization/english/modifiers/wc_modifiers_l_english.yml
> + corruption_disease_modifier:0 "Corrupted Plague"
punctuation

2024-09-20 12:42 UTC, robmart commented on common/modifiers/wc_genocide_modifiers.txt
> +	epidemic_resistance = 5
No, depopulation would cause the diseases to spread slower. The concept was lifted from CK2.

2024-09-20 12:59 UTC, robmart commented on common/council_tasks/wc_genocide_councilor_tasks.txt
> +		}
Yes, that's how it's handled in the vanilla tasks

2024-09-20 13:00 UTC, robmart commented on common/on_action/game_start.txt
> +		}
Fixed in cdbca0e10b978e445ff07d98f46ee86844cfbf44

2024-09-20 13:02 UTC, robmart commented on common/on_action/wc_genocide_on_actions.txt
> +        250 = 0
I don't really understand why it's done that way either, but it's how vanilla does it

2024-09-20 13:42 UTC, robmart commented on common/scripted_effects/wc_genocide_effects.txt
> +    }
Yes, fixed in df2ef2606b436234aabdc5e12a992a6bfd50cfd0

2024-09-20 13:45 UTC, robmart commented on common/scripted_triggers/wc_religious_triggers.txt
>  	}
Other doctrines will need to be added there in the future, like the ones for the evil Light religions. I suppose the OR isn't really needed now though.

2024-09-20 13:49 UTC, robmart commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
Fixed in 6acbaf6a9773bebabb3fe5f66a50bbeb27064caf

2024-09-20 13:49 UTC, robmart commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
Fixed in 6acbaf6a9773bebabb3fe5f66a50bbeb27064caf

2024-09-20 13:49 UTC, robmart commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
Fixed in 6acbaf6a9773bebabb3fe5f66a50bbeb27064caf

2024-09-20 13:49 UTC, robmart commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
Fixed in 6acbaf6a9773bebabb3fe5f66a50bbeb27064caf

2024-09-20 13:49 UTC, robmart commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
Fixed in 6acbaf6a9773bebabb3fe5f66a50bbeb27064caf

2024-09-20 13:49 UTC, robmart commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
Fixed in 6acbaf6a9773bebabb3fe5f66a50bbeb27064caf

2024-09-20 13:49 UTC, robmart commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
Fixed in 6acbaf6a9773bebabb3fe5f66a50bbeb27064caf

2024-09-20 13:50 UTC, robmart commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
Fixed in 6acbaf6a9773bebabb3fe5f66a50bbeb27064caf

2024-09-20 13:50 UTC, robmart commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
Fixed in 6acbaf6a9773bebabb3fe5f66a50bbeb27064caf

2024-09-20 13:50 UTC, robmart commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
Fixed in 6acbaf6a9773bebabb3fe5f66a50bbeb27064caf

2024-09-20 13:50 UTC, robmart commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
Fixed in 6acbaf6a9773bebabb3fe5f66a50bbeb27064caf

2024-09-20 13:51 UTC, robmart commented on events/councillor_task_events/wc_genocide_task_events.txt
> +        }
Fixed in be279cfb459eed1fb5ee2a910463991d24398853

2024-09-20 13:53 UTC, robmart commented on localization/english/modifiers/wc_modifiers_l_english.yml
> + corruption_disease_modifier:0 "Corrupted Plague"
The names shouldn't have punctuation though?

2024-09-20 14:02 UTC, robmart commented on events/councillor_task_events/wc_genocide_task_events.txt
> +    }
Fixed in a0cf3dc6a7844af0a6a0f1f6b0d5c584cb6450c4

2024-09-20 14:26 UTC, robmart commented
> since we're using the conversion speed game rule to also affect genocide, it would be wise to note that in the conversion speed game rule text

Fixed in 1499f96bfd1af02f125f5d9b59564321c773092e

2024-09-20 17:29 UTC, helloruhe commented on localization/english/modifiers/wc_modifiers_l_english.yml
> + corruption_disease_modifier:0 "Corrupted Plague"
disregard

2024-09-20 17:30 UTC, helloruhe approved these changes
LGTM

2024-09-22 15:32 UTC, merged