Light lifestyle
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #1420
Opened 2024-08-11 08:35 UTC by helloruhe

## Changelog:
- Added this thing.
- Changed that thing.

## Developer changelog:
- Added this thing.
- Changed that thing.

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:

2024-09-16 23:16 UTC, Rimaka94 commented
## Test Criteria
:x: Check that **spells** are working as their Descriptions state.
:x: Check that **perks** are working as their Descriptions state.

_Marks:_
✅ - working as expected
❌ - not working as expected
⚠️ - was unable to confirm if working as expected, needs more testing/confirmation
🔶 - may or may not be an issue, noted for your discretion

## In-depth Testing
### 📖 Initiate Branch
- :white_check_mark: **Flash of Light (Rank 1)** correctly heals Wounded on self & others.
  - :white_check_mark: Correctly reduces stages of wounds on self & others.
  - :x: Health Traits such as One-Eyed, Crippled, Holy Wrath, and possibly others are allowing casting of Flash of Light (Rank 1) despite not being able to cure these.
<details>
<summary>Flash of Light Rank 1 health traits and missing localization</summary>
Can reproduce on at least One-Eyed, Crippled, and Holy Wrath traits.

![image](https://github.com/user-attachments/assets/504335e7-b8d4-4653-bde1-d47df2cff5da)
</details>

- :white_check_mark: **Flash of Light (Rank 2)** correctly heals illnesses on self & others.
  - :white_check_mark: Correctly reduces stages of magical injuries on self & others. (tested 3 stages of frostbite/burn on myself & targets)
- :white_check_mark: **Flash of Light (Rank 3)** correctly heals debilitating illnesses on self & others. (no current magical injuries to test)
- :white_check_mark: _Divine Service_ correctly gives +0.5 Chaplain progress bonus to tasks.
- :white_check_mark: **Purify** correctly removes a negative magic effect.
  - :large_orange_diamond: **Purify** can be cast regardless of if target has negative magic effect. May not be an issue.
- :white_check_mark: **Holy Fire** properly applies Holy Fire modifier.
- :white_check_mark: **Lightwell** correctly adds positive modifier.
- :white_check_mark: _Blessed Blood_ is applied to you permanently. Applied to primary heir for 10 years.
- :white_check_mark: _Radiant Hearth_ correctly gives 25% speed & 25% Safety to your character for travelling.
- :white_check_mark: **Ritual: Salvation**
  - :white_check_mark: Correctly gives **Salvation** modifier to target character, if not Undead.
  - :white_check_mark: Correctly saves target from a possible death. Removes Salvation modifier, gives Lingering Death modifier. Both opinion modifiers look correct.
  - :white_check_mark: Correctly gives event to target when target is saved. 
  - :white_check_mark: Localization/effects are proper on different target faiths. (tested Holy Light, Yogg-Saroni, Celestial)
  - :white_check_mark: Correctly gives event to caster when target is saved.
  - :white_check_mark: Correctly cannot be cast on self nor characters with Demon trait.
  - :white_check_mark: Correctly removes an Undead trait from target, does not gain positive modifier, gains Lingering Death modifier.
  - :large_orange_diamond: There is no real "feedback" to the caster besides the 'has completed its casting' notification when spell is cast on an Undead target. Not an issue, feels as if it needs an event.
  - :large_orange_diamond: Similar to above, the target has no option to accept/decline and the only notification is the 'spell casted on you' notification and 'undead trait removed' toast. It feels as if an event should be added similar to saving someone from death, but please keep in mind this is not an issue with the spell and not a requirement.
- :x: _Echo of Light_ is not applying to characters. The toast popup does not specify a character, possible scoping issue.
<details>
<summary>Echo of Light toast</summary>
Toast shows like this regardless of targeting self/others

![image](https://github.com/user-attachments/assets/a6093d3f-9b2c-4bb5-aac0-0927e3e32791)
</details>

### ⚔️ Zealot Branch
- :white_check_mark: **Judgement** is properly revealing secrets on spell hit.
  - :x: Localization of tooltip on hoverover in spellbook does not match the actual effect.
  - :x: 'Secret Exposed' banner is showing no text when exposing Magic lifestyle secrets. It is correct on non-Magic secrets.
<details>
<summary>Judgement spellbook hover tooltip</summary>

![image](https://github.com/user-attachments/assets/3cde7083-0f1d-4305-9035-e1b3800fa5d8)
</details>

<details>
<summary>Judgement secret exposed magic user</summary>

![image](https://github.com/user-attachments/assets/4c8b795b-18fe-4efc-b555-77fa462c2b65)
</details>

- :white_check_mark: _Holy Struggle_ properly increases Mana Conductivity by 1%, all resists by 1.
- :white_check_mark: **Exorcism (Rank 1)** correctly applies negative modifier to non-undead/demonic/oldgod heritages, and correctly stacks.
  - :white_check_mark: Correctly applies/worsens Burn to Undead/Demon/Old God traits. (tested vs Undead trait, Qiraji culture (void beings), Shath'yar culture (void beings), Mantid culture (void beings), and Demon trait)
  - :large_orange_diamond: It might be worth changing Spellbook hover tooltip of Exorcism; it states it'll inflict burn vs a culture that has Undead/Demonic/Old God heritage or similar, but it appears to be taking into account trait and culture. For example, Moroes has Undead trait but Stormwindian culture (Arathi heritage) but is still counted as valid as he is Undead. Another example, if Emperor Vek'lor (Qiraji / Void Being traits) decides to change to Kaldorei culture, he is still a valid target to gain/worsen burn. A character of Damned culture but no Undead trait is a valid target for exorcism as well.
- :white_check_mark: **Exorcism (Rank 2)** Correctly applies effects of Rank 1 to multiple targets when spell hits on individual targets.
- :white_check_mark: **Explusion** correctly removes non-Congenital psychological illnesses.
  - :large_orange_diamond: **Expulsion** does not see characters with the Congenital versions of these traits as valid targets, but this might be expected.
- :white_check_mark: _Seal of Command_ gives +2 Martial bonus. 10% chance to gain +10 legitimacy on Light spell casts working properly.
- :white_check_mark: ⚠️  _Divine Purpose_ correctly applies Divine Purpose modifier to self and heir, uncertain if effect works properly. (less chance of dying in battle)
  - :white_check_mark: +5 General Opinion and -25% Tyranny is properly applied.
- :white_check_mark: **Avenging Wrath** properly applied Holy Wrath health trait to target.
  - ⚠️ I was unable to get the effect "When targeted by hostile spells, small chance of getting/increasing Burned" to trigger when spamming Holy Fire/Frostbolt on a target which has Holy Wrath.
- :white_check_mark: _Holy Retribution_ properly has chance to make Demons incapable. In my test, made incapable on 2 of 4 casts.
- :white_check_mark: **Ritual: Divine Storm** properly targets characters residing physically in the targeted Duchy.
  - :white_check_mark: Void/Demon/Undead trait characters in the Duchy are properly receiving Burned/Wounded/Holy Wrath at proper chance percentages.
  - :white_check_mark: Caster is properly receiving a Burned, Wounded, or Holy Wrath trait on spell cast.
  - :white_check_mark: Counties in the targeted Duchy are properly receiving a 1 year negative modifier, `Divine Storm`.
  - ⚠️ I did not see any Void/Demon/Undead characters immediately die on these tests as the Spellbook hoverover tooltip suggests.

### 🛡️ Templar Branch
- :white_check_mark: **Bless** is properly granting a random Magical blessing, scaling duration based on ranks 1/2/3, on self & others.
- :x: _Virtue_ only seems to be giving at maximum 1% increased Mana Conductivity, even with 2/3/4 Virtuous traits.
  - ⚠️ Uncertain of what the 'associates more likely to defend you when magic secret is revealed' effect should do.
- :white_check_mark: **Divine Shield** properly applies effect to target.
  - :white_check_mark: Properly blocks a hostile non-Light spell, then is consumed.
  - :x: Spellbook hover tooltip and effect tooltip do not match in a few ways, I believe the Spellbook hover tooltip is outdated so I am basing my tests on what the Effect states. Spellb [...]

2024-09-17 15:37 UTC, robmart requested changes

2024-09-17 15:37 UTC, robmart commented on common/script_values/wc_magic_spell_values.txt
> +						var:current_spell_rank ?= 1
You don't need the `has_variable` *and* the `?=`

Applies to multiple places in this file

2024-09-17 15:37 UTC, robmart commented on common/script_values/wc_magic_spell_values.txt
> +wc_spell_backdraft_cost_base_mana_value = 6
Why are you going back to magic numbers instead of using the values?

2024-09-17 15:37 UTC, robmart commented on common/scripted_effects/wc_magic_effects.txt
> +        }
The burned and frostbite can be simplified into their own effect with an argument.

2024-09-17 15:37 UTC, robmart commented on common/scripted_effects/wc_magic_effects.txt
> +        }
`change_trait_rank = { trait = burned rank = -1 }` will remove the trait if the rank is `1`, so no need to have an exception for `frostbite_1` and `burned_1`

2024-09-17 15:37 UTC, robmart commented on common/scripted_effects/wc_magic_effects.txt
> +        }
Can change the limit to `has_trait = burned` etc

2024-09-17 15:37 UTC, robmart commented on common/scripted_effects/wc_magic_effects.txt
> +        }
Why is the `holy_wrath` bit needed? Shouldn't it use the `random_character_trait` portion below?

2024-09-17 15:37 UTC, robmart commented on common/scripted_effects/wc_magic_effects.txt
> +remove_injury_effect = {
Same comments as in `remove_magic_injury_effect`

2024-09-17 15:37 UTC, robmart commented on common/scripted_effects/wc_magic_light_effects.txt
> +            days = wc_current_spell_duration
You aren't saving the duration before using it in on_actions. It will be applied forever.

2024-09-17 15:37 UTC, robmart commented on localization/english/event_localization/wc_magic_lifestyle_events_l_english.yml
> +  secret_exposed_notification_effect_message_disorder_magic:0 "[owner.GetTitledFirstNamePossessive] practice of Fel magic was exposed by [secret_exposer.GetTitledFirstName]!"
Use the magic names and not the forces before Mariuso sees.

2024-09-17 15:37 UTC, robmart commented on localization/english/event_localization/wc_magic_lifestyle_events_l_english.yml
> +  secret_exposed_notification_effect_message_disorder_magic.i_exposed:0 "I have exposed [owner.GetTitledFirstNamePossessive] practice of Fel magic!"
Mariuso trigger

2024-09-18 03:48 UTC, helloruhe commented on common/script_values/wc_magic_spell_values.txt
> +wc_spell_backdraft_cost_base_mana_value = 6
because its from old lifestyle and i didnt update it yet

2024-09-18 03:51 UTC, helloruhe commented on common/script_values/wc_magic_spell_values.txt
> +wc_spell_backdraft_cost_base_mana_value = 6
also, no values for duratioin

2024-09-18 03:59 UTC, helloruhe commented on localization/english/event_localization/wc_magic_lifestyle_events_l_english.yml
> +  secret_exposed_notification_effect_message_disorder_magic.i_exposed:0 "I have exposed [owner.GetTitledFirstNamePossessive] practice of Fel magic!"
lol

2024-09-18 04:05 UTC, merged