Feat/code/rtp government
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #1528
Opened 2024-10-22 09:15 UTC by edmund-h

## Changelog:
- Night Elves will start with Administrative Government by default. This can be disabled via a gamerule
- Completely reorganized the Kaldorei Empire and added 26 new Noble Family titles at the start of gameplay.
- Nightelf names should sound more Lore Accurate now (removed most randomly generated names)
- Replaced dynasty names so that they make more sense
- Added some intrigue within the Kaldorei Empire; certain ambitious and driven individuals who will stop at nothing to secure their place in Kaldorei society
- Removed the ability to play as Theocracy and Republic because of major issues that broke Vanilla and RTP features. These will be readded as versions of Administrative Government in the future.

## Developer changelog:
- Consolidated Night Elf dynasty files into one
- English localization for all new names

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:

2024-10-22 10:04 UTC, edmund-h commented on common/culture/name_lists/wc_tauren.txt
> +		Kodorat Kodort Kohanott Koralen Kordolon Kordorn Kordovind Korrel'hsu Korrel'tay Korvako Ksanarut Ksandoban Ksanhapik Ksannarok Ksanrel'rut
this change had to be made because of a key hash collision with one of the new names

2024-10-22 10:04 UTC, edmund-h commented on common/culture/name_lists/wc_vrykulic.txt
> +		Uldgar Ulf Ulfar Vaettfang Valdemar Vegard Vigfus Voldgar Ymor
i moved this name because it looked better as a vrykulic name and it was less work than deleting it completely

2024-10-22 10:04 UTC, edmund-h commented on history/characters/gilblin.txt
> +	name = Gizmix
these gilblins used the wrong namelist so i changed these names to use the correct one

2024-10-22 10:04 UTC, edmund-h commented on common/culture/name_lists/wc_taunka.txt
> +		Kodorat Kodort Kohanott Koralen Kordolon Kordorn Kordovind Korrel'hsu Korrel'tay Korvako Ksanarut Ksandoban Ksanhapik Ksannarok Ksanrel'rut
had to change this name because of a key collision with one of the new nightelf names; changing this was less work than going through dozens of new names one by one

2024-10-22 10:04 UTC, edmund-h commented on common/dynasties/128000_night_elf.txt
> +﻿### 128000 series nightelf names ###
`1000000_night_elf.txt` had a namespace conflict with vanilla and should never have been left in during the ck2->ck3 transition. I consolidated everything into one file and unified the naming conventions somewhat.

2024-10-22 10:07 UTC, edmund-h commented on common/dynasties/128000_night_elf.txt
> +# 100070 = { name = "dynn_Darkwalker" culture = night_elf }\
```suggestion
# 100070 = { name = "dynn_Darkwalker" culture = night_elf }
```

2024-10-29 17:59 UTC, ElMariuso requested changes
You should fix conflicts with dev branch first, to be sure everything is okay with dev changes.

2024-10-30 22:24 UTC, Rimaka94 commented
- :x: `Order Mass Arrests` decision requirement has a localization error, "Empire of Kaldorei's Tier is a **TIER**"
<details>
<summary>[SCREENSHOT] Order Mass Arrests loc</summary>

![image](https://github.com/user-attachments/assets/c48dac3a-da34-4eeb-8cb9-7efa720441d2)
</details>

- :x: Lady Sylvanas in 603 and Lady Vereesa 605 are both listed as landless Administrative estates of the title **D_nf_20016**, and can be seen when going to the Landless Rulers tab in character select on these two dates. Neither are part of a greater Administrative Realm, so not sure what sort of bugs this could cause.
- 🔶 Is it intended for Priesthood of Elune head of faith title to have Administrative succession rules? I'm assuming it's intended to just follow your realm's succession rules.

2024-10-30 22:28 UTC, Rimaka94 commented
- 🔶 Landless Night Elf administrative rulers only show up as valid selections under the Landless Rulers tab starting with the 605 date, is this intended or should they be available in earlier bookmarks as well?

2024-10-30 23:06 UTC, edmund-h commented
> * 🔶 Landless Night Elf administrative rulers only show up as valid selections under the Landless Rulers tab starting with the 605 date, is this intended or should they be available in earlier bookmarks as well?

this is normal, as the Nightelves have lost significant land and the noble families have become landless.

2024-10-31 00:21 UTC, edmund-h commented
> * ❌ `Order Mass Arrests` decision requirement has a localization error, "Empire of Kaldorei's Tier is a **TIER**"
> 
> [SCREENSHOT] Order Mass Arrests loc
> ![image](https://private-user-images.githubusercontent.com/55721682/381755586-c48dac3a-da34-4eeb-8cb9-7efa720441d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMjk2ODQsIm5iZiI6MTczMDMyOTM4NCwicGF0aCI6Ii81NTcyMTY4Mi8zODE3NTU1ODYtYzQ4ZGFjM2EtZGEzNC00ZWViLThjYjktN2VmYTcyMDQ0MWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDIzMDMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZmE4MTVkYmVkZmFjNGNjODQ1OTA5ZTMwYjZkOGYzODVkYzU2YmQ5NTE4MWJlYzg3MTQ1ODFiZGI4MzNlY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.135JBAeQml2r9gcZqn1lMLXzag0PmHQ4ryghwQpOnSk)

this is a vanilla issue 
<img width="850" alt="Screenshot 2024-10-30 at 8 19 49 PM" src="https://github.com/user-attachments/assets/5c824b51-8e55-432b-b338-80241438603d">

2024-10-31 19:52 UTC, ElMariuso approved these changes
I can't check more rn but I imagine we don't have time anymore 
Prepare an hotfix in case of

2024-10-31 20:24 UTC, merged