Holy Light in french
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #1534
Opened 2024-10-22 17:28 UTC by ElMariuso

## Changelog:
- Translate all Holy Light branch files into french

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
- Check the files

2024-12-28 16:04 UTC, hamjustine commented on localization/french/artifacts/wc_artifacts_l_french.yml
> + maraad_memento.desc:0 "Un diadème brisé et terni ayant appartenu à Leran, la soeur du Redresseur de torts Maraad. Elle le portait comme symbole de grâce, jusqu'à ce qu'elle soit violée et tuée par l
"sœur"

2024-12-28 16:04 UTC, hamjustine commented on localization/french/culture/wc_culture_titles_l_french.yml
> + abbey_theocracy_northshire:0 "Abbaye"
pas de diff entre duc et conte ? genre abbé / grand abbé ou un truc du genre ?

2024-12-28 16:04 UTC, hamjustine commented on localization/french/event_localization/religion_events/wc_religious_interaction_events_l_french.yml
> + wc_religious_interaction.1011:0 "Nous avons bien reçu votre lettre, [actor.GetTitledFirstName]. L'Inquisition vous remercie pour votre reddition volontaire. Des agents sont déjà en route pour vous p
je ferais une légère modif de ce genre : 
Sachez que cela ne vous épargnera pas les rigueurs de la véritable pénitence, mais votre choix de ne pas fuir ou combattre l'Inquisition pourrait inspirer la confiance de certains.

2024-12-28 16:04 UTC, hamjustine commented on localization/french/event_localization/religion_events/wc_religious_interaction_events_l_french.yml
> + wc_religious_interaction.1021:0 "Vous êtes suspecté d'avoir trahi les préceptes de [actor.GetFaith.HighGodNameAlternate]. Trop longtemps, vos actions sont passées inaperçues, mais cela prend fin auj
jugé/jugée custom_loc_FR
pareil pour marqué

2024-12-28 16:04 UTC, hamjustine commented on localization/french/event_localization/religion_events/wc_religious_interaction_events_l_french.yml
> + wc_religious_interaction.1011.deceitful:0 "Je savais que cela finirait ainsi, je suis prêt."
prêt/prête

2024-12-28 16:04 UTC, hamjustine commented on localization/french/event_localization/religion_events/wc_religious_interaction_events_l_french.yml
> + wc_religious_interaction.1110:0 "Votre prisonnier, [recipient.GetFirstName], est arrivé sain et sauf, et nous sommes ravis que vous l’ayez envoyé pour se repentir sous notre guidance. L'Inquisition
arrivé/arrivée

2024-12-28 16:04 UTC, hamjustine commented on localization/french/event_localization/religion_events/wc_religious_interaction_events_l_french.yml
> + wc_religious_interaction.1115:0 "Votre présence impie a corrompu mes cachots bien trop longtemps. Ma foi m'a donné sagesse et force, et avec le conseil des [actor.GetFaith.PriestNeuterPlural], j'ai
ma foi m'a donné/donnée

2024-12-28 16:04 UTC, hamjustine commented on localization/french/wc_traits_l_french.yml
> + trait_scarlet_mark_character_desc:0 "[ROOT.GetCharacter.GetFirstNameNoTooltip] a été déclaré hérétique par l'Inquisition, le marquant comme une cible pour une traque implacable et une justice puniti
a été déclaré/déclarée

2024-12-28 16:04 UTC, hamjustine commented on localization/french/wc_relationship_reasons_l_french.yml
> + rival_requested_scarlet_mark:0 "[TARGET_CHARACTER.GetShortUIName|U] a demandé la marque écarlate de [CHARACTER.GetShortUINamePossessive]."
a demandé de récupérer sa marque ou de marquer le perso ? j'ai un doute vu que j'ai pas le contexte

2024-12-28 16:04 UTC, hamjustine commented on localization/french/wc_decisions_l_french.yml
> + create_pandaria_decision.t.mogu:0 "Restore the Mogu Empire"
ça manque de français :3

2024-12-28 16:04 UTC, hamjustine commented on localization/french/wc_decisions_l_french.yml
> + wc_at_war_against_crisis_trigger_tt:0 "Engagé dans une guerre défensive contre une crise majeure menaçant le royaume."
Je sais pas si le sujet est un territoire ou un perso, voir le contexte afin de savoir si un accord est nécessaire à "Engagé"

2024-12-28 16:04 UTC, hamjustine commented on localization/french/wc_decisions_l_french.yml
>   develop_the_undercity:0 "Développer la Fossoyeuse"
retirer le "la"

2024-12-28 16:04 UTC, hamjustine commented on localization/french/wc_decisions_l_french.yml
>   develop_the_undercity_tooltip:0 "Déplacez la capitale sous terre"
Si c'est une décision, je mettrais plutôt "Déplacer" (je sais que tu n'as pas touché ces parties, mais je vois la faute ça m'embête :D

2024-12-28 16:04 UTC, hamjustine commented on localization/french/wc_decisions_l_french.yml
> + form_the_silver_hand_decision_tooltip:0 "Vengez les frères tombés et poursuivez leur mission pour défendre notre foi et nos terres"
autant y a plein d'endroit où mettre le féminin et le masculin ca peut être chiant/moche (genre paladins et paladines), autant je pense que là on peut dire frères et sœurs

2024-12-28 16:04 UTC, hamjustine commented on localization/french/wc_decisions_l_french.yml
> + form_the_silver_hand_decision_desc:0 "Avec la chute de Comté-du-Nord, la Lumière nous offre un choix. Allons-nous venger nos frères tombés au combat et nous unir en tant que paladins de la Sainte Lu
même remarque que plus bas concernant frères et sœurs

2024-12-28 16:04 UTC, hamjustine commented on localization/french/event_localization/wc_holy_light_orders_events_l_french.yml
> + wc_holy_light_orders_events.0001.desc.azerothian:0 "Cela représente un coup dévastateur tant pour l’[holy_light.ReligiousHeadTitleName] que pour l'esprit de notre peuple.\n\n[high_priest.GetName] a
est ce possible d'avoir un haut prêtre femme ? si oui il/elle décidera

2024-12-28 16:04 UTC, hamjustine commented on localization/french/event_localization/wc_holy_light_orders_events_l_french.yml
> + wc_holy_light_orders_events.0001.desc.holy_light:0 "Cela représente un coup dévastateur pour l’$k_holy_light_church$, et prouve que nous ne pouvons plus ignorer la menace orque.\n\nL’[ROOT.Char.Fait
il / elle décidera

2024-12-28 16:04 UTC, hamjustine commented on localization/french/event_localization/wc_major_decisions_events_l_french.yml
> + wc_holy_order_decision.0001.desc:0 "L’ennemi a prouvé qu'il ne reculerait devant rien pour massacrer des innocents. Partout où ils passent, leurs guerriers massacrent sans pitié, y compris dans les
m'a supplié/e

2024-12-28 16:04 UTC, hamjustine commented on localization/french/modifiers/wc_holy_light_orders_modifiers_l_french.yml
> + spy_the_brotherhood_modifier_desc:0 "Ce personnage a infiltré la Fraternité de Comté-du-Nord."
$ c_northshire $ plutôt ?

2024-12-28 16:04 UTC, hamjustine commented on localization/french/wc_custom_titles_l_french.yml
> + d_northwoods:0 "Comté-du-Nord"
Bois-du-Nord ?

2024-12-28 16:04 UTC, hamjustine commented on localization/french/modifiers/wc_holy_light_orders_modifiers_l_french.yml
> + spy_the_brotherhood_modifier_desc:0 "Ce personnage a infiltré la Fraternité de Comté-du-Nord."
d'ailleurs est ce qu'il faut pas mettre  holy_order_brotherhood_of_northshire ?

2024-12-28 16:29 UTC, ElMariuso commented on localization/french/culture/wc_culture_titles_l_french.yml
> + abbey_theocracy_northshire:0 "Abbaye"
Non parce-que l’abbé est duc justement, ça sonnerait bizarre sinon.
C'est spécifique a Northshire aussi

2024-12-28 16:29 UTC, ElMariuso commented on localization/french/artifacts/wc_artifacts_l_french.yml
> + maraad_memento.desc:0 "Un diadème brisé et terni ayant appartenu à Leran, la soeur du Redresseur de torts Maraad. Elle le portait comme symbole de grâce, jusqu'à ce qu'elle soit violée et tuée par l
Fait

2024-12-28 16:29 UTC, ElMariuso commented on localization/french/event_localization/religion_events/wc_religious_interaction_events_l_french.yml
> + wc_religious_interaction.1011:0 "Nous avons bien reçu votre lettre, [actor.GetTitledFirstName]. L'Inquisition vous remercie pour votre reddition volontaire. Des agents sont déjà en route pour vous p
Fait

2024-12-28 16:29 UTC, ElMariuso commented on localization/french/event_localization/wc_holy_light_orders_events_l_french.yml
> + wc_holy_light_orders_events.0001.desc.azerothian:0 "Cela représente un coup dévastateur tant pour l’[holy_light.ReligiousHeadTitleName] que pour l'esprit de notre peuple.\n\n[high_priest.GetName] a
Euh oui...

2024-12-28 16:29 UTC, ElMariuso commented on localization/french/modifiers/wc_holy_light_orders_modifiers_l_french.yml
> + spy_the_brotherhood_modifier_desc:0 "Ce personnage a infiltré la Fraternité de Comté-du-Nord."
Marche pas ici

2024-12-28 16:29 UTC, ElMariuso commented on localization/french/wc_custom_titles_l_french.yml
> + d_northwoods:0 "Comté-du-Nord"
Non j'ai change completement en Comte du Nord en anglais aussi

2024-12-28 16:29 UTC, ElMariuso commented on localization/french/wc_decisions_l_french.yml
> + wc_at_war_against_crisis_trigger_tt:0 "Engagé dans une guerre défensive contre une crise majeure menaçant le royaume."
C'est un perso ouais

2024-12-28 16:29 UTC, ElMariuso commented on localization/french/wc_decisions_l_french.yml
>   develop_the_undercity:0 "Développer la Fossoyeuse"
C'est fait

2024-12-28 16:29 UTC, ElMariuso commented on localization/french/wc_decisions_l_french.yml
>   develop_the_undercity_tooltip:0 "Déplacez la capitale sous terre"
Fait

2024-12-28 16:29 UTC, ElMariuso commented on localization/french/wc_decisions_l_french.yml
> + form_the_silver_hand_decision_tooltip:0 "Vengez les frères tombés et poursuivez leur mission pour défendre notre foi et nos terres"
Ca serait trop long

2024-12-28 16:29 UTC, ElMariuso commented on localization/french/wc_decisions_l_french.yml
> + form_the_silver_hand_decision_desc:0 "Avec la chute de Comté-du-Nord, la Lumière nous offre un choix. Allons-nous venger nos frères tombés au combat et nous unir en tant que paladins de la Sainte Lu
Pareil qu'en bas

2024-12-28 16:29 UTC, ElMariuso commented on localization/french/wc_decisions_l_french.yml
> + create_pandaria_decision.t.mogu:0 "Restore the Mogu Empire"
Je ferais pas ca ici, c'est juste histoire d'avoir une sorte de gros TODO et eviter les erreurs de loc pour le moment

2024-12-28 16:29 UTC, ElMariuso commented on localization/french/wc_relationship_reasons_l_french.yml
> + rival_requested_scarlet_mark:0 "[TARGET_CHARACTER.GetShortUIName|U] a demandé la marque écarlate de [CHARACTER.GetShortUINamePossessive]."
marquer, j'ai change.

2025-01-06 00:05 UTC, ElMariuso commented on localization/french/event_localization/religion_events/wc_religious_interaction_events_l_french.yml
> + wc_religious_interaction.1011.deceitful:0 "Je savais que cela finirait ainsi, je suis prêt."
Fait

2025-01-06 00:05 UTC, ElMariuso commented on localization/french/event_localization/religion_events/wc_religious_interaction_events_l_french.yml
> + wc_religious_interaction.1021:0 "Vous êtes suspecté d'avoir trahi les préceptes de [actor.GetFaith.HighGodNameAlternate]. Trop longtemps, vos actions sont passées inaperçues, mais cela prend fin auj
Fait

2025-01-06 00:05 UTC, ElMariuso commented on localization/french/event_localization/religion_events/wc_religious_interaction_events_l_french.yml
> + wc_religious_interaction.1110:0 "Votre prisonnier, [recipient.GetFirstName], est arrivé sain et sauf, et nous sommes ravis que vous l’ayez envoyé pour se repentir sous notre guidance. L'Inquisition
Fait

2025-01-06 00:05 UTC, ElMariuso commented on localization/french/event_localization/religion_events/wc_religious_interaction_events_l_french.yml
> + wc_religious_interaction.1115:0 "Votre présence impie a corrompu mes cachots bien trop longtemps. Ma foi m'a donné sagesse et force, et avec le conseil des [actor.GetFaith.PriestNeuterPlural], j'ai
C'est la foi qui a donné

2025-01-06 00:05 UTC, ElMariuso commented on localization/french/event_localization/wc_holy_light_orders_events_l_french.yml
> + wc_holy_light_orders_events.0001.desc.azerothian:0 "Cela représente un coup dévastateur tant pour l’[holy_light.ReligiousHeadTitleName] que pour l'esprit de notre peuple.\n\n[high_priest.GetName] a
Fait

2025-01-06 00:05 UTC, ElMariuso commented on localization/french/event_localization/wc_holy_light_orders_events_l_french.yml
> + wc_holy_light_orders_events.0001.desc.holy_light:0 "Cela représente un coup dévastateur pour l’$k_holy_light_church$, et prouve que nous ne pouvons plus ignorer la menace orque.\n\nL’[ROOT.Char.Fait
Fait

2025-01-06 00:05 UTC, ElMariuso commented on localization/french/event_localization/wc_major_decisions_events_l_french.yml
> + wc_holy_order_decision.0001.desc:0 "L’ennemi a prouvé qu'il ne reculerait devant rien pour massacrer des innocents. Partout où ils passent, leurs guerriers massacrent sans pitié, y compris dans les
fait

2025-01-06 00:05 UTC, ElMariuso commented on localization/french/wc_traits_l_french.yml
> + trait_scarlet_mark_character_desc:0 "[ROOT.GetCharacter.GetFirstNameNoTooltip] a été déclaré hérétique par l'Inquisition, le marquant comme une cible pour une traque implacable et une justice puniti
fait

2025-01-06 11:43 UTC, hamjustine requested changes

2025-01-06 11:43 UTC, hamjustine commented on localization/french/event_localization/religion_events/wc_religious_interaction_events_l_french.yml
> + wc_religious_interaction.1110:0 "Votre prisonnier, [recipient.GetFirstName], est arrivé[recipient.Custom('FR_E')] sain et sauf, et nous sommes ravis que vous l’ayez envoyé pour se repentir sous notr
"saine et sauve" et "que vous l'ayez envoyé(e)"

2025-01-06 11:46 UTC, ElMariuso commented on localization/french/event_localization/religion_events/wc_religious_interaction_events_l_french.yml
> + wc_religious_interaction.1110:0 "Votre prisonnier, [recipient.GetFirstName], est arrivé[recipient.Custom('FR_E')] sain et sauf, et nous sommes ravis que vous l’ayez envoyé pour se repentir sous notr
Fait

2025-01-06 11:55 UTC, hamjustine commented on localization/french/event_localization/religion_events/wc_religious_interaction_events_l_french.yml
> + wc_religious_interaction.1024:0 "[recipient.GetTitledFirstName], vous portez la marque, vous désignant comme hérétique. Les fautes qui ont conduit à votre marquage n'ont pas été pardonnées, mais nou
le temps que vous avez passé marqué(e)

2025-01-06 11:55 UTC, hamjustine commented on localization/french/wc_decisions_l_french.yml
> + wc_at_war_against_crisis_trigger_tt:0 "Engagé dans une guerre défensive contre une crise majeure menaçant le royaume."
du coup engagé(e), mais a check si ça fonctionne dans les descriptions, je crois que j'ai un doute.

2025-01-06 11:55 UTC, ElMariuso commented on localization/french/event_localization/religion_events/wc_religious_interaction_events_l_french.yml
> + wc_religious_interaction.1024:0 "[recipient.GetTitledFirstName], vous portez la marque, vous désignant comme hérétique. Les fautes qui ont conduit à votre marquage n'ont pas été pardonnées, mais nou
Fait

2025-01-06 11:56 UTC, hamjustine commented on localization/french/artifacts/wc_artifacts_l_french.yml
> + maraad_memento.desc:0 "Un diadème brisé et terni ayant appartenu à Leran, la soeur du Redresseur de torts Maraad. Elle le portait comme symbole de grâce, jusqu'à ce qu'elle soit violée et tuée par l
je vois pas la correction 🤔

2025-01-06 11:57 UTC, hamjustine commented on localization/french/artifacts/wc_artifacts_l_french.yml
> + maraad_memento.desc:0 "Un diadème brisé et terni ayant appartenu à Leran, la soeur du Redresseur de torts Maraad. Elle le portait comme symbole de grâce, jusqu'à ce qu'elle soit violée et tuée par l
ha si, t'as corrigé 1 sur 2 des "soeurs"

2025-01-06 11:58 UTC, ElMariuso commented on localization/french/artifacts/wc_artifacts_l_french.yml
> + maraad_memento.desc:0 "Un diadème brisé et terni ayant appartenu à Leran, la soeur du Redresseur de torts Maraad. Elle le portait comme symbole de grâce, jusqu'à ce qu'elle soit violée et tuée par l
Mieux ?

2025-01-06 12:10 UTC, hamjustine approved these changes

2025-01-06 12:11 UTC, merged