Night Elf Facial Markings
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #255
Opened 2021-03-26 19:06 UTC by ercarp

## Changelog:
- Added **8** facial markings for the Night Elf ethnicity based on the ones used in _World of Warcraft_.
  - _One marking ("Shadow") is still missing. This will be added later._
- The markings are used by Night Elf females with the **_Elunic_** religion. There is a small chance for the game to spawn in characters without markings, but the majority (98%) of Night Elves have them.
  - Additionally, characters with the **_Zealous_** trait are guaranteed to always have markings.
- Markings base their color off the character's hair color.
- Markings have been added to Ruler Designer and Barbershop.

<details><summary>Click to view image</summary>

![image](https://user-images.githubusercontent.com/78575425/112681109-eb4e6280-8e76-11eb-8524-10e3a52098c0.png)

</details>

### To-do:
- An event or decision for acquiring facial markings as a rite of adulthood. This will be done on a different branch, however.

# How to test:

1. Start up the game (**revert to 1.2.2 if you're using 1.3** as the current branch is not compatible with the newest patch yet) and view the markings in-game or in the Ruler Designer.
2. Provide feedback in the comments and if needed, make suggestions how you think they could be improved visually.

2021-03-27 11:41 UTC, Deuce20201 requested changes
Markings look good. 

But 98% of females generate the marking but not Tyrande Whisperwind. 

![20210327063904_1](https://user-images.githubusercontent.com/76598749/112719535-3752e300-8f1b-11eb-8f9f-cbfb6a451f68.jpg)

![Tyrande_Whisperwind](https://user-images.githubusercontent.com/76598749/112719541-4174e180-8f1b-11eb-9aa8-a82b2306bb33.jpg)

2021-03-27 15:24 UTC, ercarp commented
> But 98% of females generate the marking but not Tyrande Whisperwind.

Tyrande will likely have custom DNA eventually with unique markings, so this isn't that big of a deal.

2021-03-27 16:06 UTC, Deuce20201 commented
> > But 98% of females generate the marking but not Tyrande Whisperwind.
> 
> Tyrande will likely have custom DNA eventually with unique markings, so this isn't that big of a deal.

In that case I have no other criticisms.

2021-03-27 16:06 UTC, Deuce20201 approved these changes

2021-03-27 16:24 UTC, zumbak04 commented on gfx/portraits/portrait_modifiers/wc_facial_markings.txt
> +				NOT = { has_trait = zealous }
I would make it so:
Only those who have the Cynical trait don't have markings.

2021-03-28 10:02 UTC, TheGroxEmpire reviewed
Some bright hair colors from generated character (ruler designer and in game) are giving really bright color markings that are imo weird:
<details>

![image](https://user-images.githubusercontent.com/47816228/112748457-e3f99700-8fe5-11eb-9c8e-469d849d1dcf.png)
![image](https://user-images.githubusercontent.com/47816228/112748482-07bcdd00-8fe6-11eb-83d3-67b3f6499070.png)
![image](https://user-images.githubusercontent.com/47816228/112748496-21f6bb00-8fe6-11eb-9194-eab1fd74bf97.png)
![image](https://user-images.githubusercontent.com/47816228/112748511-3e92f300-8fe6-11eb-9d75-afc039fedbf8.png)

</details>

2021-03-28 21:58 UTC, TheDrPibb1999 commented
got the same weird color as grox

2021-03-31 06:40 UTC, ercarp commented
@TheGroxEmpire @TheDrPibb1999 This has to do with the blend mode used for the markings in `common/genes/wc_gene_facial_markings.txt`. There are four blend modes to choose from: `overlay`, `replace`, `hard_light`, and `multiply`. The current one being used is `overlay`, and there is a reason for it which I will try to illustrate.

**Overlay** seems to work best with mid-range colors. **Multiply** with dark and mid-range colors (lighter colors are very faded, some of them don't show at all). **Hard Light** and **Replace** function very similarly.

If you want the colors to be exact, then Replace would probably be the best option for a blend mode, but it can also look a bit too much like paint. I suggest you navigate to the file mentioned above and switch around the blend modes to see which ones you personally think look best.

<details><summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/78575425/113101195-1af9c380-9205-11eb-91e3-c0514cd2ce03.png)

</details>

2021-03-31 14:44 UTC, TheGroxEmpire reviewed
Thank you for the detailed explanation. Would it be possible to limit the range that it the marking color may be generated? Color like white, light pink, etc might not just be suitable for markings color.

Most of the markings are pretty good given the right color. My next suggestion will be to increase the opacity on them. The base opacity is around half slider in ruler designer:
<details>

Base opacity:
![image](https://user-images.githubusercontent.com/47816228/113146165-8a010780-9259-11eb-88aa-7f5d12020bb5.png)
![image](https://user-images.githubusercontent.com/47816228/113146286-ac932080-9259-11eb-8e89-e80e99afbad1.png)
![image](https://user-images.githubusercontent.com/47816228/113146486-ed8b3500-9259-11eb-9f9f-5de110f34d06.png)


Increased opacity:
![image](https://user-images.githubusercontent.com/47816228/113146199-95ecc980-9259-11eb-9890-d7a5b5afae25.png)
![image](https://user-images.githubusercontent.com/47816228/113146321-b4eb5b80-9259-11eb-8c3b-3f8d269adfa2.png)
![image](https://user-images.githubusercontent.com/47816228/113146514-f7ad3380-9259-11eb-8597-a38b537609a2.png)
</details>

One more thing, I found that the dark green haired Nelves have almost black markings, this is pretty unusual for me. It could be a bit more green colored imo:
<details>

![image](https://user-images.githubusercontent.com/47816228/113148622-3d6afb80-925c-11eb-84e7-f32eae08c6b1.png)
</details>

2021-04-03 20:15 UTC, TheDrPibb1999 commented
Personally, IMO i disagree with "One more thing, I found that the dark green haired Nelves have almost black markings, this is pretty unusual for me. It could be a bit more green-colored imo" I think the sage brown is more fitting and the green almost looks too much like paint, and same for the opacity, the markings are tattoos, so it would make sense for them to have an almost faded appearance, again all IMO :)

2021-05-30 16:05 UTC, DatFrenchBanana requested changes
Tested on MAC 10.13.6. Crusader Kings 3 version 1.3.2(Corvus) with no other mod. Had visual problems for the skin of vanilla ruler designer made characters.

2021-07-03 17:35 UTC, zumbak04 commented
> Thank you for the detailed explanation. Would it be possible to limit the range that it the marking color may be generated? Color like white, light pink, etc might not just be suitable for markings color.

Don't see it as a problem. Why you don't like white and pink?

> Most of the markings are pretty good given the right color. My next suggestion will be to increase the opacity on them. The base opacity is around half slider in ruler designer:

Changed in 0624e214e56c740796a9afeda76eacd0096d1707.

> One more thing, I found that the dark green haired Nelves have almost black markings, this is pretty unusual for me. It could be a bit more green colored imo:

There are 2 types of blend modes: the first doesn't handle well bright colors (they're too bright and break lighting) and the second doesn't handle well dark colors (the one we use).

2021-07-03 17:35 UTC, zumbak04 commented
> Tested on MAC 10.13.6. Crusader Kings 3 version 1.3.2(Corvus) with no other mod. Had visual problems for the skin of vanilla ruler designer made characters.

Confirm it still exists on the new CK3 version, please.

2021-07-04 12:39 UTC, Deuce20201 approved these changes
Still works and looks good to me.

2021-07-05 12:17 UTC, CantTouchThisJinTao approved these changes
Tested via ruler designer and didn't notice any issues, markings looked good on varying opacity (except obviously the lower ones where it's barely visible - but I haven't come across any even close to that in-game so no issue there). Also tested in-game (with mixed races as well e.g. NE-Troll/NE-Orc/NE-Gnome/NE-Ogre). Markings look really good, noticed no issues. Tested via giving zealous trait to unmarked females and the facial markings appeared.

Only thing I can really think of is having specific markings relate to specific traits (if that's even possible) e.g. brave = chance of Blades, Bear or Claws etc. But the females in lore can choose which marking they want so it's not really necessary.
Overall I really like these markings and therefore approve considering I personally haven't come across any issues.

2021-07-05 12:43 UTC, zumbak04 commented
> Only thing I can really think of is having specific markings relate to specific traits (if that's even possible) e.g. brave = chance of Blades, Bear or Claws etc. But the females in lore can choose which marking they want so it's not really necessary.

That's for another PR.

2021-07-05 14:16 UTC, TheGroxEmpire reviewed
> Don't see it as a problem. Why you don't like white and pink?

It's just not a usual color for these markings. Combined with already pink / white skin color on some Night Elves, it is bit weird to have those facial marking colors. Although, it is less of an issue now that the opacity has been increased.

- The Tyrande and Azshara facial markings have different color blend mode to the rest:
<details>

![image](https://user-images.githubusercontent.com/47816228/124484770-0285e000-ddd6-11eb-92e9-14c463dbb404.png)
![image](https://user-images.githubusercontent.com/47816228/124484792-0ade1b00-ddd6-11eb-9704-b95d14852ad8.png)
![image](https://user-images.githubusercontent.com/47816228/124484847-1fbaae80-ddd6-11eb-9b4f-ee291bd0d073.png)

![image](https://user-images.githubusercontent.com/47816228/124484725-f568f100-ddd5-11eb-968f-543132764c31.png)

2021-07-05 14:17 UTC, zumbak04 commented
> * The Tyrande and Azshara facial markings have different color blend mode to the rest:

Yep, it's intended.

2021-07-05 14:22 UTC, TheGroxEmpire approved these changes
Looks good to me then!

2021-07-05 16:09 UTC, hamjustine approved these changes

2021-07-09 16:46 UTC, DatFrenchBanana approved these changes

2021-07-09 20:39 UTC, merged