#246 review
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #275
Opened 2021-04-03 06:01 UTC by MemeWizard

## Developer changelog:
- This is part of review for #246

2021-04-03 22:50 UTC, zumbak04 requested changes

2021-04-03 22:50 UTC, zumbak04 commented on common/traits/00_traits.txt
> -			}
It fits Wastewanders.

2021-04-03 22:50 UTC, zumbak04 commented on events/religion_events/great_holy_war_events.txt
> -	}
There's no option now.

2021-04-03 22:50 UTC, zumbak04 commented on events/religion_events/great_holy_war_events.txt
> -	}
There's no option now.

2021-04-04 07:53 UTC, MemeWizard commented on events/religion_events/great_holy_war_events.txt
> -	}
＞︿＜???
![image](https://user-images.githubusercontent.com/46576860/113502273-f28b0580-9533-11eb-913e-ef871bda1c4b.png)

2021-04-04 07:54 UTC, MemeWizard commented on events/religion_events/great_holy_war_events.txt
> -	}
＞︿＜???
![image](https://user-images.githubusercontent.com/46576860/113502289-12bac480-9534-11eb-84a7-0f2b44b6dd61.png)

2021-04-04 08:03 UTC, MemeWizard commented on common/traits/00_traits.txt
> -			}
If you say so

2021-04-04 11:15 UTC, zumbak04 requested changes

2021-04-04 11:15 UTC, zumbak04 commented on events/religion_events/great_holy_war_events.txt
> -		}
It may fit the Wastewanders.

2021-04-04 11:52 UTC, zumbak04 approved these changes
LGTM!

2021-04-04 17:03 UTC, merged