Highmountain Tauren race trait
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #306
Opened 2021-04-11 09:21 UTC by robmart

## Changelog:
- Added Highmountain Tauren race trait

# How to test: Set culture to highmountain the the character creator

# Note:
- Doesn't yet have an icon. Waiting on Rundt for that.

2021-04-11 16:22 UTC, zumbak04 requested changes

2021-04-11 16:22 UTC, zumbak04 commented on localization/english/wc_traits_l_english.yml
> + trait_creature_highmountain_tauren_desc:0 "The Highmountain Tauren are an offshoot of Tauren descended from Huln Highmountain, who was an ally of the Kaldorei Resistance during the War of the Ancien
I wouldn't mention lifespan because... I feel like the desc is narrative, so we shouldn't use game terms there.

2021-04-11 16:22 UTC, zumbak04 commented on common/scripted_triggers/wc_portrait_triggers.txt
> +potential_race_highmountain_tauren_trigger = {
Not placed in...
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/114311917-bcd0b880-9b01-11eb-8a8a-1b0709b4ac7d.png)

</details>

2021-04-12 16:07 UTC, zumbak04 approved these changes
LGTM!

2021-04-12 16:27 UTC, arithon approved these changes
loc LGTM

2021-04-12 17:01 UTC, merged