Revert "Revert "Merge pull request #312 from Warcraft-GoA-Development…
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #322
Opened 2021-04-12 18:44 UTC by panpoleon

…-Team/top-hat""

This reverts commit c7cdd880f4b16224f6bb9bb6f449fc4c2c493996.
(GDC)

I accidently merged pls make it back :c

2021-04-15 22:48 UTC, zumbak04 requested changes

2021-04-15 22:48 UTC, zumbak04 commented on gfx/models/portraits/attachments/female_headgears/secular/goblin/gallywix_hat_01/female_headgear_secular_goblin_gallywix_hat_01.asset
> +﻿pdxmesh = {
The female top hat clips with the head sometimes.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/114947423-2f24fe00-9e5e-11eb-96d3-e7b978475f9c.png)

</details>

2021-04-16 16:20 UTC, Grimlawck submitted a review, later dismissed

2021-04-16 16:45 UTC, Grimlawck requested changes
I went through the years 583-605 and the kings and Emperor had their top hats. However, there is one particular Duke who has a top hat as well even though he isn't a king. Duke Jazikrax of Booty Bay and this persists throughout all time periods.
<details>
<summary>Click to expand</summary>

![](https://i.gyazo.com/e2378e3fc787f29f0a08800714e3fea8.png)

</details>

In 603 it appears the characters don't have their top hats but after clicking on them their portraits corrected themselves.  (Notice the child before and after as well)
<details>
<summary>Before</summary>

![](https://i.gyazo.com/e5e4dbeb5ecbde3c2e5ac7543f3a2968.png)

</details>

<details>
<summary>After</summary>

![](https://i.gyazo.com/3e5bb153bb41b9db05c11849355018b2.png)

</details>

In 605 all is normal besides the Duke spoken about previously so I wont bother with a picture.

2021-04-17 20:28 UTC, zumbak04 commented
> I went through the years 583-605 and the kings and Emperor had their top hats. However, there is one particular Duke who has a top hat as well even though he isn't a king. Duke Jazikrax of Booty Bay and this persists throughout all time periods.

Fixed in 68ef6e1f08f0eac91373488caeeab1509e7a6a5e.

> In 603 it appears the characters don't have their top hats but after clicking on them their portraits corrected themselves. (Notice the child before and after as well)

It's fine. The Character Finder may be outdated, it updates on clicking characters.

2021-04-18 02:33 UTC, Grimlawck approved these changes
Once again I went through the different time periods just to be thorough. With the new changes, I see that the spouses of the rulers don't have any top hats anymore and the Duke that was mentioned previously no longer has one either. So everything looks as though it is intended.

2021-04-18 18:40 UTC, zumbak04 approved these changes
I wonder if you can make coloring patterns. It would make hats x10 better. Anyway, the current one LGTM!

2021-04-19 05:10 UTC, TheDrPibb1999 approved these changes
A hat fit for a trade-prince!!!

2021-04-23 20:49 UTC, zumbak04 requested changes

2021-04-23 20:49 UTC, zumbak04 commented on common/culture/cultures/goblin.txt
>  	graphical_cultures = {
It's just black for me.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115928287-eccf7280-a496-11eb-8e4f-d3c133711426.png)

</details>

2021-04-23 22:01 UTC, zumbak04 requested changes

2021-04-25 07:36 UTC, Grimlawck commented on common/culture/cultures/goblin.txt
>  	graphical_cultures = {
I agree that it is kind of hard to tell the difference between the two colors because of how dark they are.

2021-04-25 08:11 UTC, Grimlawck approved these changes
Unless the new hats I saw in the development chat were supposed to be in this pull everything LGTM! All seems to work between the different time periods as well. Female top hat for the female rulers looks great as well.

2021-04-25 09:35 UTC, zumbak04 approved these changes
LGTM!

2021-04-25 18:14 UTC, merged