Trogg and Drogbar religion
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #344
Opened 2021-04-22 14:25 UTC by robmart

## Changelog:
- Added Trogg religion
- Added Drogbar religion

# TODO:
- Trogg religion loc (Need a name suggestion)
- Trogg religion icon (something based on a salamander/lizard)

# How to test:

2021-04-22 21:03 UTC, zumbak04 commented on localization/english/religion/wc_religion_l_english.yml
> + trogg_religion_desc:0 "Shal'danalism are the Nightwell traditions. Its followers depend on and are changed by the Nighwell's power, the Shal'danalists favor the arcane philosophy of their past as th
A name idea is here. The description is to be written by some English Proofreader, ping them in the dev.
```suggestion
 trogg_religion:0 "Salamandrism" #Placeholder
 trogg_religion_adj:0 "Salamandric"
 trogg_religion_adherent:0 "Salamandrist"
 trogg_religion_adherent_plural:0 "Salamandrists"
 trogg_religion_desc:0 "We smash and worship salamanders (placeholder)."
```
Source: https://wowpedia.fandom.com/wiki/Trogg#Culture

2021-04-25 10:15 UTC, zumbak04 requested changes

2021-04-25 10:15 UTC, zumbak04 commented on common/religion/religions/shamanism_group.txt
> +			doctrine = doctrine_elemental_earth_magic_approved #Drogbar have strong control over earth
IIRC, you can't have 2 approved doctrines. So one must go.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115989685-8d757d80-a5d0-11eb-8c88-54226888b257.png)

</details>

2021-04-25 10:15 UTC, zumbak04 commented on common/religion/religions/shamanism_group.txt
> +			doctrine = doctrine_elemental_earth_magic_approved #Drogbar have strong control over earth
I would say that the drogbar wouldn't mind the Decay.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/115989703-aaaa4c00-a5d0-11eb-959f-a2ea840bcdeb.png)

</details>

2021-04-26 18:42 UTC, zumbak04 commented on common/religion/religions/shamanism_group.txt
> +			#Ignore all except some shaman, they don't know any other magic
This guy can into Fire magic too.

2021-04-26 18:57 UTC, zumbak04 requested changes

2021-04-26 18:57 UTC, zumbak04 commented on common/religion/religions/shamanism_group.txt
> +			doctrine = doctrine_elemental_earth_magic_approved #Drogbar have strong control over earth
I propose these laws for both faiths:
Shadow - Ignored or Shunned, they're primitive and don't care for bad magic use
Fel - Ignored or Shunned, they're primitive and don't care for magic use
Death - Ignored or Shunned, they're primitive and don't care for magic use
Decay - Approved, they don't worship elements thus don't mind enslaving them
Fire - Accepted, troggs use it and they live close to lava and stuff.
Air - Ignored, their counter-magic.
Earth - Idolised... well, you know.

2021-04-28 17:59 UTC, zumbak04 requested changes

2021-04-28 17:59 UTC, zumbak04 commented on common/religion/holy_sites/wc_holy_sites.txt
> +		monthly_prestige_gain_per_knight_add = 0.1
Balanced it [Here](https://docs.google.com/spreadsheets/d/18zS-FAte6nsejx7rpzSmVuioRXps3iWSvSkx_xRJSWI/edit?usp=sharing).
```suggestion
		martial = 1
		monthly_prestige_gain_per_knight_add = 0.2
```

2021-04-28 17:59 UTC, zumbak04 commented on common/religion/religions/shamanism_group.txt
> +			doctrine = doctrine_elemental_earth_magic_approved #Drogbar have strong control over earth
Only one magic can be Idolised.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/116450884-e2cdbb00-a86c-11eb-9a7d-bd8b0c060ad7.png)

</details>

2021-04-28 17:59 UTC, zumbak04 commented on common/religion/holy_sites/wc_holy_sites.txt
> +alterac_valley = {
Not localized.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/116451020-0f81d280-a86d-11eb-8fe8-2b54e2a505e1.png)

</details>

2021-04-28 18:19 UTC, zumbak04 approved these changes
LGTM!

2021-04-29 21:49 UTC, hamjustine approved these changes

2021-05-01 12:47 UTC, arithon approved these changes
loc LGTM

2021-05-01 12:50 UTC, merged