Beyoud the Dark Portal
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #446
Opened 2021-06-15 01:53 UTC by zumbak04

## Changelog:
- WIP

## Developer changelog:
- WIP

# How to test:

2021-06-30 04:06 UTC, ercarp requested changes
Made some suggestions on how I personally think the text could be improved on at some parts. There were also a couple of grammar mistakes that I fixed, but for the most part the localization seems fine to me.

2021-06-30 04:06 UTC, ercarp commented on localization/english/event_localization/wc_draenor_events_l_english.yml
> + WCDRA_1025_DESC:0 "The world is ending! During your assault on the Black Temple, the sky darkens and the ground begins to quake- Ner'zhul's ritual is complete!\n\nIt is unclear whether he understood
```suggestion
 WCDRA_1025_DESC:0 "The world is ending! During your assault on the Black Temple, the sky suddenly darkens and the ground begins to quake - Ner'zhul's ritual is complete!\n\nOne must wonder whether or not he understood the grim price he would pay for his ambition. Several new portals have opened, but their tremendous energies are out of control! The very fabric of this world is being torn asunder, irrevocably dooming Draenor.\n\nThere is nothing more you can do. You must lead your troops back to the Dark Portal or be destroyed alongside this dying world!"
```

2021-06-30 04:06 UTC, ercarp commented on localization/english/event_localization/wc_draenor_events_l_english.yml
> + WCDRA_1030_DESC:0 "The Laughing Skull, one of the many savage orc clans infesting with world, bar your path. Maniacal and bloodthirsty even by orc standards, the Laughing Skull are known for madness
```suggestion
 WCDRA_1030_DESC:0 "The Laughing Skull, one of the many savage orc clans infesting this world bar your path. Maniacal and bloodthirsty even by orc standards, the Laughing Skull are known for madness and treachery.\n\nThese ones offer you a truce, however, if you agree to aid them in battle against their enemies, the Thunderlord and Bonechewer clans. A combined strike would probably be less costly than open battle against these orcs, but can you really trust these savages?"
```

2021-06-30 04:06 UTC, ercarp commented on localization/english/event_localization/wc_draenor_events_l_english.yml
> + WCDRA_1040_DESC:0 "It is done.\n\nThe Dark Portal, the source of so much chaos and suffering, finally lies silent. Draenor, the world on the other side, is likewise no more. The shattered and twiste
```suggestion
 WCDRA_1040_DESC:0 "It is done.\n\nThe Dark Portal, the source of so much chaos and suffering, finally lies silent. Draenor, the world on the other side, is likewise no more. The shattered and twisted remains of it are now known as Outland.\n\nAzeroth is hardly unscathed either. The lands around the Dark Portal are blasted and lifeless, and the devastation left by the Orcish Horde is apparent everywhere, but no further threats should emerge from the portal any time soon. The brave heroes on the other side made the ultimate sacrifice to preserve their world, and for now at least, they appear to have succeeded."
```

2021-06-30 14:26 UTC, ercarp approved these changes
Localization looks good to me!

2021-07-02 14:35 UTC, Samio321 approved these changes
Event fired, chose "Over my dead body", was declared on by 6800 ogres. Ouch. I would say this is unbalanced considering the hard-fought war you would probably have just fought against the orcs but at the same time I suppose that's the whole point.
<details>
<summary>Ogre and army screenie</summary>

![image](https://user-images.githubusercontent.com/38307424/124287643-42bb3900-db1e-11eb-9273-515910b4f9e1.png)

![image](https://user-images.githubusercontent.com/38307424/124287934-96c61d80-db1e-11eb-892c-621ce896f12e.png)
</details>

Then got another event after winning said war with yesman stating that he could lead an expedition himself to stop Elder Shaman Ner'Zhul.
<details>
<summary>Event screenie</summary>

![image](https://user-images.githubusercontent.com/38307424/124288353-1653ec80-db1f-11eb-9f74-147311cb585b.png)
</details>

Waited a few months then got this...

<details>
<summary>Event screenie</summary>

![image](https://user-images.githubusercontent.com/38307424/124288560-5024f300-db1f-11eb-95a2-ea9a6701d5f2.png)

![image](https://user-images.githubusercontent.com/38307424/124288648-6e8aee80-db1f-11eb-9cb1-4b935aa6bfbb.png)

</details>

Chose the top option, then met Grizzik. Chose bottom option which didn't seem to make much difference(?) and then died trying to escape the dying world. Got a final event as the heir.

In other words, all events seemed to fire on first run through. 
Second run through didn't get the ogres, but still got the Ner'zhul event.
Third run through, same things, everything seems okay. Stable and all that, but I did get an event about a raid on my land in the meantime which was humorous. Not sure how you'd fix that sort of thing.

2021-07-02 14:57 UTC, zumbak04 commented
> Event fired, chose "Over my dead body", was declared on by 6800 ogres. Ouch. I would say this is unbalanced considering the hard-fought war you would probably have just fought against the orcs but at the same time I suppose that's the whole point.

Do you find 4000 max reasonable?

> Chose bottom option which didn't seem to make much difference(?) and then died trying to escape the dying world. Got a final event as the heir.

It makes the next event firing faster/slower.

2021-07-02 16:18 UTC, Samio321 commented
> Do you find 4000 max reasonable?

That sounds more reasonable, considering what my levies were at the time.

2021-07-05 16:15 UTC, CantTouchThisJinTao commented
> > Event fired, chose "Over my dead body", was declared on by 6800 ogres. Ouch. I would say this is unbalanced considering the hard-fought war you would probably have just fought against the orcs but at the same time I suppose that's the whole point.
> 
> Do you find 4000 max reasonable?
> 
> > Chose bottom option which didn't seem to make much difference(?) and then died trying to escape the dying world. Got a final event as the heir.
> 
> It makes the next event firing faster/slower.

I tested the event, had 8.4k raiders spawn and beat them pretty easily (I did ally with Lordaeron at game start though so they provide around 5k troops ontop of my 3k (they managed to take the 3 dark portal regions and then sailed to Stormwind where i caught up to them with Lordaeron's troops). I'd say 4k max might be too easy when taking allies into consideration.. it does depend on who the player allies with though. It'd be extremely hard fighting those numbers if you had no allies.

<details>
<summary>Click to expand</summary>

![DarkportalRaider8-4kstack](https://user-images.githubusercontent.com/86842532/124498230-ea9d6480-ddb3-11eb-9d5c-ff56dfb01359.png)
</details>

2021-07-05 16:39 UTC, CantTouchThisJinTao approved these changes
Tested event thoroughly (every option), progressed as intended. No issues detected.

2021-07-06 19:11 UTC, merged