Ported orcish coas from ck2
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #493
Opened 2021-06-29 16:19 UTC by MemeWizard

#### Changelog:
- Ported orcish coas from ck2

2021-06-30 11:57 UTC, zumbak04 requested changes

2021-06-30 11:57 UTC, zumbak04 commented on common/coat_of_arms/template_lists/colored_emblem_lists.txt
>  			100 	= "ce_frostwolf.dds"
They should be moved up.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/123956471-c7417680-d9bb-11eb-995e-8e68b250470c.png)

</details>

2021-06-30 12:08 UTC, zumbak04 commented on common/coat_of_arms/template_lists/colored_emblem_lists.txt
>  			100 	= "ce_frostwolf.dds"
Nevermind, wait till my answer.

2021-07-02 10:12 UTC, zumbak04 approved these changes
LGTM!

2021-07-06 20:32 UTC, Remerod approved these changes
It all looked good to me!
Nicely done.

2021-07-06 22:59 UTC, MemeWizard commented
@zumbak04 @Remerod thanks for reviews

2021-07-06 23:00 UTC, merged