87 mercenary names
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #507
Opened 2021-07-05 17:55 UTC by SolTsuki

Created all unique mercenary names for all cultures so far #87 

Summary:
- Warcraft-Guardians-of-Azeroth-2\common\culture\cultures - Changed every specific culture so they have specific mercenary groups.
- Warcraft-Guardians-of-Azeroth-2\localization\english\wc_mercenaries_l_english.yml - Added all English descriptions for mercenary names here.

2021-07-05 19:56 UTC, zumbak04 requested changes
Don't be afraid to use not-unique or the same name for different cultures. In the vanilla, there is a ton of mercenaries labeled band or company.

A lot of my comments are about assuming mercenary composition. There are 2 ways to fix it:
- Not assume it
- Change this composition per cultures (so some will have mages by default)

If you ask me, I like the second one.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_cthun_guard:0 "C'thun's Guard"
This assumes the qiraji worship C'Thun. They may not. Mercenaries are a cultural thing.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_priests_of_yshaarj:0 "Priests of Y'Shaarj"
It's weird to see priests and mercenaries.
The mantid may not worship Y'Shaarj.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_manari_lords:0 "Man'ari lords of [TITLE.GetNameNoTierNoTooltip]"
Names are capitalized.
```suggestion
 mercenary_company_manari_lords:0 "Man'ari Lords of [TITLE.GetNameNoTierNoTooltip]"
```

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_gunners:0 "Gunners of [TITLE.GetNameNoTierNoTooltip]"
It assumes they consist of gunners. It may not. They may be heavy infantry.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_gryphon_riders:0 "Gryphon Riders of [TITLE.GetNameNoTierNoTooltip]"
It assumes they consist of gryphon riders.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_warmages_of_sun:0 "Warmages of the Sun"
It assumes they consist of mages.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_bloodmages:0 "Bloodmages of [TITLE.GetNameNoTierNoTooltip]"
It assumes they consist of mages.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_warmages_of_moon:0 "Warmages of the Moon"
It assumes they consist of mages.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_arcanists:0 "Arcanists of [TITLE.GetNameNoTierNoTooltip]"
It assumes they consist of mages.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_warmages_of_stars:0 "Warmages of the Stars"
It assumes they consist of mages.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_shamans:0 "Shamans of [TITLE.GetNameNoTierNoTooltip]"
It assumes they consist of shamans. They may be light infantry.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_warmages:0 "Warmages of [TITLE.GetNameNoTierNoTooltip]"
It assumes they consist of mages.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_sea_wizards:0 "Sea Wizards of [TITLE.GetNameNoTierNoTooltip]"
It assumes they consist of mages.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_orcs_demise:0 "Orc's Demise"
This name is problematic because:
- They may be no orcs (if we make a bookmark before the Dark Portal)
- They may be hired by orcs.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_warmages_of_shore:0 "Warmages of the Shore"
It assumes they consist of mages.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_geomancers:0 "Geomancers of [TITLE.GetNameNoTierNoTooltip]"
It assumes they consist of mages.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_slavemasters:0 "slavemasters of [TITLE.GetNameNoTierNoTooltip]"
```suggestion
 mercenary_company_slavemasters:0 "Slavemasters of [TITLE.GetNameNoTierNoTooltip]"
```

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_oracles:0 "Oracles of [TITLE.GetNameNoTierNoTooltip]"
It assumes they consist of mages.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_tendrils_of_void:0 "tendrils of the Void"
```suggestion
 mercenary_company_tendrils_of_void:0 "Tendrils of the Void"
```

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_faceless_ones:0 "Faceless Onees"
```suggestion
 mercenary_company_faceless_ones:0 "Faceless Ones"
```

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_elemental_benders:0 "Elemental Benders of [TITLE.GetNameNoTierNoTooltip]"
It assumes they consist of mages.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_pyromancers:0 "Pyromancers of [TITLE.GetNameNoTierNoTooltip]"
It assumes they consist of mages.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_sunpriests:0 "Sunpriests of [TITLE.GetNameNoTierNoTooltip]"
It assumes they consist of mages.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_runemasters:0 "Runemasters of [TITLE.GetNameNoTierNoTooltip]"
It assumes they consist of mages.

2021-07-05 19:56 UTC, zumbak04 commented on localization/english/wc_mercenaries_l_english.yml
> + mercenary_company_deathdruids:0 "Deathdruids of [TITLE.GetNameNoTierNoTooltip]"
It assumes they consist of mages.

2021-07-08 15:29 UTC, zumbak04 requested changes

2021-07-08 15:29 UTC, zumbak04 commented on common/culture/cultures/orc.txt
> +			{ name = "mercenary_company_warlocks_of_the_sea" }
Warlocks?

2021-07-08 15:29 UTC, zumbak04 commented on common/culture/cultures/orc.txt
> +			{ name = "mercenary_company_shamans" }
Shamans?

2021-07-08 15:29 UTC, zumbak04 commented on common/culture/cultures/undead.txt
> +			{ name = "mercenary_company_inmortal_company" }
inmortal?

2021-07-09 21:38 UTC, zumbak04 approved these changes
LGTM! Goob job!

2021-07-15 21:41 UTC, elcascavel approved these changes
LGTM as well!

2021-07-16 08:42 UTC, merged