Demonic Government
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #542
Opened 2021-07-20 19:11 UTC by zumbak04

## Changelog:
- Added this thing.
- Changed that thing.

## Developer changelog:
- Added this thing.
- Changed that thing.

# Tasks:

# How to test:

2021-08-17 17:27 UTC, LordSilvermane reviewed
One suggestion, otherwise looks good.

2021-08-17 17:27 UTC, LordSilvermane commented on localization/english/wc_government_l_english.yml
> + demonic_government_desc:0 "\n$game_concept_demonic_government_desc$\n\n#F Demonic hordes that came out of the Twisting Nether to bring havoc. Their immortal souls are hungry for pain and tortures ca
```suggestion
 demonic_government_desc:0 "\n$game_concept_demonic_government_desc$\n\n#F Demonic hordes that have come out of the Twisting Nether to wreak havoc. Their immortal souls are always hungry for pain and suffering inflicted upon mortal civilizations.#!"
```

2021-08-18 00:43 UTC, CantTouchThisJinTao requested changes
Most seems to be working as intended, however:

- Torturing doesn't result in gaining frenzy (I assume that's what was meant and not torturers - either way torturing and the torturer trait don't give frenzy)
- Shivarran have the nathrezim trait (is this intended).
- Eredar do not have the demon trait (or have modifiers added to their trait - I guess this is intended though since draenei have the same trait).

2021-08-18 01:49 UTC, LordSilvermane approved these changes
LGTM!

2021-08-18 02:16 UTC, zumbak04 commented
> * Torturing doesn't result in gaining frenzy (I assume that's what was meant and not torturers - either way torturing and the torturer trait don't give frenzy)

I can't confirm.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/129825806-b36ec8f7-255f-48ae-9e71-2b2efc4c94c4.png)

</details>


> * Shivarran have the nathrezim trait (is this intended).

Fixed in 217c61fde67a1a6a2d433ae69a87ab7a94d37a68.

2021-08-18 02:19 UTC, zumbak04 commented
> I can't confirm.

But may be fixed in 6b4db066020baade95370247fdee79fef98a9e92. So worth testing on your side again.

2021-08-18 02:23 UTC, CantTouchThisJinTao commented
> > * Torturing doesn't result in gaining frenzy (I assume that's what was meant and not torturers - either way torturing and the torturer trait don't give frenzy)
> 
> I can't confirm.
> 
> Click to expand
> > * Shivarran have the nathrezim trait (is this intended).
> 
> Fixed in [217c61f](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/commit/217c61fde67a1a6a2d433ae69a87ab7a94d37a68).

Yeah torture seems to give dark frenzy now, shivarran have their trait as well.

I'll approve now then.

2021-08-18 02:23 UTC, CantTouchThisJinTao approved these changes

2021-08-18 02:39 UTC, zumbak04 commented
> * Eredar do not have the demon trait (or have modifiers added to their trait - I guess this is intended though since draenei have the same trait).

Fixed in 18c94fd54027eeff36f2b94d54673c3663f40b74

2021-08-18 09:45 UTC, CantTouchThisJinTao commented
> > * Eredar do not have the demon trait (or have modifiers added to their trait - I guess this is intended though since draenei have the same trait).
> 
> Fixed in [18c94fd](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/commit/18c94fd54027eeff36f2b94d54673c3663f40b74)

Can confirm starting as Demonic Eredar via ruler designer gives the Demon trait, none of the already existing one's have it though.

2021-08-18 13:43 UTC, arithon approved these changes
loc LGTM

2021-08-18 14:57 UTC, zumbak04 commented
> Can confirm starting as Demonic Eredar via ruler designer gives the Demon trait, none of the already existing one's have it though.

Fixed in a1aca54691b220ad7b4e9982e9c6b3fb49ccbfdc.

2021-08-18 16:35 UTC, CantTouchThisJinTao approved these changes
Everything seems to be working now

2021-08-29 07:40 UTC, TheGroxEmpire reviewed
- Torturing non ruler is still not rewarding Dark Frenzy:
<Details>

![image](https://user-images.githubusercontent.com/47816228/131242566-1696e0c8-73c7-40ea-923d-b58e15cd1eab.png)
</details>

> If you want combat or army bonuses, I can make the demonic army stronger instead of cheaper. May pick one of these bonuses.

I'm fine with that. I think aggressive attackers (+25% Enemy Fatal Casualties) is thematic and doesn't tip the balance too much.

2021-08-29 13:04 UTC, zumbak04 commented
> Torturing non ruler is still not rewarding Dark Frenzy:

Ruler or close relative of a ruler (spouse, child).

2021-08-29 15:48 UTC, zumbak04 commented
> I'm fine with that. I think aggressive attackers (+25% Enemy Fatal Casualties) is thematic and doesn't tip the balance too much.

Done in c62d8d9ad12de023a9fcab8eb9bf05fa3bba54f5.

2021-08-29 17:43 UTC, TheGroxEmpire approved these changes
Everything seems to be working as intended. My suggestion was also implemented.

2021-08-31 13:02 UTC, merged