Death flags
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #556
Opened 2021-07-24 20:38 UTC by runtd

## Changelog:
-Added colored emblems for death religion characters and titles

2021-07-24 22:22 UTC, zumbak04 requested changes
Just want to say that this CoA looks ideal. Fits well.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/126881342-e474c946-0185-4d8e-8840-e4e9724b9574.png)

</details>

2021-07-24 22:22 UTC, zumbak04 commented on common/coat_of_arms/template_lists/colored_emblem_lists.txt
> +			100 	= "ce_skull3.dds"
Should be bigger and lowered.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/126882281-f43a3374-4c4e-4484-96fa-f834d1c4ffed.png)
![image](https://user-images.githubusercontent.com/46384992/126882308-bb4bd5af-4f92-4cda-99a1-cbe621069e10.png)

</details>

2021-07-24 22:22 UTC, zumbak04 commented on common/coat_of_arms/template_lists/colored_emblem_lists.txt
> +			100 	= "ce_spider.dds"
Should be lowered.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/126882318-2bce9e34-f01c-4c89-94bd-b2358a25f51f.png)

</details>

2021-07-25 17:06 UTC, zumbak04 requested changes

2021-07-25 17:06 UTC, zumbak04 commented on common/coat_of_arms/template_lists/colored_emblem_lists.txt
> +			100 	= "ce_skull3.dds"
Still too small.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/126907216-acc91f04-973b-455f-ad0f-52079de2c74d.png)

</details>

2021-07-25 17:06 UTC, zumbak04 commented on common/coat_of_arms/template_lists/colored_emblem_lists.txt
> +			100 	= "ce_abomination.dds"
I would increase the contrast. It's very hard to notice these features.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/126907349-b91f8116-b6bc-4cc6-9bcf-dc2cd5e7939a.png)

</details>

2021-07-26 22:00 UTC, zumbak04 approved these changes
LGTM! Good job!

2021-08-12 17:48 UTC, TheDrPibb1999 approved these changes
Personally enjoy all, LGTM

2021-09-24 18:34 UTC, merged