Night Elf Markings Rework + 1 New Marking
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #679
Opened 2021-09-12 20:54 UTC by ercarp

## Changelog:
- Hand-painted every Night Elf marking from scratch in Blender.
  - I created the first iterations of the markings "blindly" in 2D using Photoshop, so they had a lot of errors that were not intended. The new markings were painted directly on the face of the character model, so they should be more detailed and accurate.

## Reworked Markings

### nightelf_markings_01 (Bear)

<details><summary>Click to expand</summary>

⭐ **New**
![image](https://user-images.githubusercontent.com/78575425/133002155-a9cc9332-4799-4e89-a094-63d42389f386.png)

**Old**
![image](https://user-images.githubusercontent.com/78575425/133001875-a1be0a50-60e1-4a8d-ae70-00170b799c15.png)

**Reference**
![image](https://user-images.githubusercontent.com/78575425/133001560-d8dda96a-2944-49b5-9360-b351d1ac1a67.png)

</details>

### nightelf_markings_02 (Blades)

<details><summary>Click to expand</summary>

⭐ **New**
![image](https://user-images.githubusercontent.com/78575425/133001349-8bf7ceba-bef1-49cd-b19e-3c871d0831eb.png)

**Old**
![image](https://user-images.githubusercontent.com/78575425/133001888-8870c0b6-5513-41a2-8795-12335fce9d83.png)

**Reference**
![image](https://user-images.githubusercontent.com/78575425/133001583-6537c195-1c98-4caf-9055-83952c5cf665.png)

</details>

### nightelf_markings_03 (Crane)

<details><summary>Click to expand</summary>

⭐ **New**
![image](https://user-images.githubusercontent.com/78575425/133001717-b78393f2-ff75-478e-bb84-3f1cfbf76771.png)

**Old**
![image](https://user-images.githubusercontent.com/78575425/133001898-7c5be23c-6353-43dc-95b5-764ff3f6907e.png)

**Reference**
![image](https://user-images.githubusercontent.com/78575425/133001590-fcd7a818-3311-4bdc-968c-eeff1ae86822.png)

</details>

### nightelf_markings_04 (Leaf)

<details><summary>Click to expand</summary>

⭐ **New**
![image](https://user-images.githubusercontent.com/78575425/133001366-3b7e654f-8c52-4997-8995-b8dc8eea3773.png)

**Old**
![image](https://user-images.githubusercontent.com/78575425/133001904-fcf3a37d-a6b8-4092-b29f-c09ab57a5716.png)

**Reference**
![image](https://user-images.githubusercontent.com/78575425/133001733-a6fcb346-9637-4f71-ac15-83809471564b.png)

</details>

### nightelf_markings_05 (Claws)

<details><summary>Click to expand</summary>

⭐ **New**
![image](https://user-images.githubusercontent.com/78575425/133001381-4804586f-7f27-4190-80c2-a197fa12b297.png)

**Old**
![image](https://user-images.githubusercontent.com/78575425/133001918-eb204e77-efe4-43f7-bde0-1d3c508f745a.png)

**Reference**
![image](https://user-images.githubusercontent.com/78575425/133001552-728cbe14-002e-4b6f-8ceb-6d053ed18de4.png)

</details>

### nightelf_markings_06 (Wings)

<details><summary>Click to expand</summary>

⭐ **New**
![image](https://user-images.githubusercontent.com/78575425/133001394-abf571ac-2ae9-4673-b9c1-03e196e4a50f.png)

**Old**
![image](https://user-images.githubusercontent.com/78575425/133001924-2dce5e9c-963f-4304-9e7d-b7558265cc33.png)

**Reference**
![image](https://user-images.githubusercontent.com/78575425/133001758-3c1b08c7-6913-4ba4-8a4c-706a6b7b5ec9.png)

</details>

### nightelf_markings_07 (Serpent)

<details><summary>Click to expand</summary>

⭐ **New**
![image](https://user-images.githubusercontent.com/78575425/133001404-be313e3b-f7ab-4b2c-bdb8-e4aeaa9d7d7e.png)

**Old**
![image](https://user-images.githubusercontent.com/78575425/133001927-0ff679d1-5b1b-4b3e-bb04-fed607203c17.png)

**Reference**
![image](https://user-images.githubusercontent.com/78575425/133001763-66313f2b-fcf3-4f1b-a32d-245c1eef0124.png)

</details>

### nightelf_markings_08 (Owl)

<details><summary>Click to expand</summary>

⭐ **New**
![image](https://user-images.githubusercontent.com/78575425/133001425-43884ffa-db0d-4baa-9787-9dc40c0db350.png)

**Old**
![image](https://user-images.githubusercontent.com/78575425/133001933-154fbc48-e789-4994-ae10-bb40c89e36c8.png)

**Reference**
![image](https://user-images.githubusercontent.com/78575425/133001766-4009bda7-1248-49f3-b842-7e0af9e5a0be.png)

</details>

## New Marking

### nightelf_markings_09 (Shadow)

<details><summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/78575425/133001461-629a4724-9801-4cf1-99a8-d4f293ea2361.png)

**Reference**
![image](https://user-images.githubusercontent.com/78575425/133001771-7273e19a-f60d-4424-836a-898f89033010.png)

</details>

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
- Compare the Night Elf markings used on `master` to the new ones on `night-elf-markings-rework`.
  - You may either view them directly in the **Ruler Designer** or **[Debug Portrait Editor](https://ck3.paradoxwikis.com/Console_commands#Enabling_debug_mode)** or by looking up **_Female_** characters with the **_Night Elf_** trait in-game using the **Character Finder**.
- Provide feedback on the reworked markings `1-8`, and the new `nightelf_markings_09`.

2021-09-13 06:30 UTC, ValianBlue commented
_¡Fantástico!_

_The leaf markings are the clear standout for me as a definite improvement, but all the markings look better than their previous iterations._

_My only suggestion is to detach the colors for the markings from the hair color._

2021-09-13 06:47 UTC, ercarp commented
> _My only suggestion is to detach the colors for the markings from the hair color._

In what way? Because we used to have them not linked, but they generated some really strange-looking elves that didn't look good at all. In comparison, basing the color of their markings on the color of their hair looked a hundred times better.

The other option would be to create nine color variations for each marking (the amount they have in WoW), which would tally up to 81 decals if I'm doing my math right. And that's just not a feasible amount considering the maximum amount of decals you can have is supposedly 100.

Either way, it's not really up to me. I suppose we could try the first option again and see if they look as bad as I remember, but there was a reason we decided to link them to hair color instead.

2021-09-13 07:01 UTC, ValianBlue commented
_Hmm, perhaps it's possible to set a list of hex value colors in code for the markings. I think it's doable since it's currently tied to hair color, but I may be wrong._

_If not, then perhaps it could be a player-only feature._

2021-09-13 13:55 UTC, zumbak04 commented
> Hmm, perhaps it's possible to set a list of hex value colors in code for the markings. I think it's doable since it's currently tied to hair color, but I may be wrong.

I don't think there's another way to get variety except ting it to some other color.

> If not, then perhaps it could be a player-only feature.

Markings? All females in night elven society have them.

2021-09-13 14:04 UTC, zumbak04 requested changes

2021-09-13 22:04 UTC, ercarp commented on localization/english/wc_portraits_l_english.yml
> + facial_nightelf_markings_09:0 "Night Shadow"
My bad. Moved them in dcc99821c7c46eba9a689b816c7543dd92327a5d.

2021-09-14 15:57 UTC, zumbak04 approved these changes
LGTM!

2021-09-16 06:19 UTC, Darknight367 approved these changes
Beautiful!

2021-09-16 12:09 UTC, CantTouchThisJinTao approved these changes
Pretty sure the new ones all look better. The old leaf shown in the screenshot I believe is a bugged one, didn't used to look that separated.
Tested in game on a few other races and looked decent as well.
Not sure if it matters but Tyrande has one of the new markings instead of her custom one.

Approved :)

2021-09-17 04:31 UTC, ercarp commented
> The old leaf shown in the screenshot I believe is a bugged one, didn't used to look that separated.

It's not bugged, I made the old markings so I know it looked like that. It just wasn't noticeable in-game because the separated parts were hidden by their eyebrows which I disabled for the preview images here.

2021-09-17 04:31 UTC, merged