Reworked elemental doctrines
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #765
Opened 2021-11-18 02:25 UTC by MemeWizard

## Changelog:
- Reworked spirit and decay magical doctrines for future usage:
  -  It's needed for future branches, so characters can potentially bully water elementals while having a good relationship with fire elementals, etc.
  - Removed 2 old (spirit&decay) doctrines
  - Added 8 spirit&decay for each element

## Dev changelog:
- Reworked a few triggers, replaced several triggers with one.

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:

2021-12-04 10:26 UTC, zumbak04 requested changes

2021-12-04 10:26 UTC, zumbak04 commented on common/religion/religions/loa_group.txt
> +			doctrine = doctrine_elemental_earth_spirit_magic_accepted
Why Hakkari aren't enslaving them?

2021-12-04 11:33 UTC, MemeWizard commented on common/religion/religions/loa_group.txt
> +			doctrine = doctrine_elemental_earth_spirit_magic_accepted
Should be fixed in 5ab32eb

2021-12-04 12:21 UTC, zumbak04 approved these changes
LGTM!

2021-12-04 13:47 UTC, riioze approved these changes
The 1st point is good but I'm sorry I didnt found the Elemental doctrines

2021-12-04 16:31 UTC, arithon approved these changes
loc LGTM (will check german later ingame, but most likely in the LC)

2022-01-11 13:14 UTC, TheGroxEmpire reviewed
- This tooltip is confusing to me. The part where it mentions two syncretism Tenets. There is a grammatical error on how the or is used here but I can't suggest changes before I understand what it meant:
<details>

![image](https://user-images.githubusercontent.com/47816228/148948723-09049def-a4cf-45f7-9a16-0736a84de6c8.png)

</details>

2022-01-21 11:58 UTC, TheGroxEmpire approved these changes
Everything else look good to me!

2022-01-21 12:01 UTC, MemeWizard commented
@zumbak04 @arithon @TheGroxEmpire  @riioze thanks for reviews <3

2022-01-21 12:02 UTC, merged