Cultural Naming Improvements (Elven Group)
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #825
Opened 2022-01-07 22:45 UTC by Loralius

## Changelog:
- Expanded library of lore-friendly character and dynastic names for High Elves, Blood Elves, Night Elves, Highborne, Nightborne and Naga.

## Developer changelog:
### Current Status and Next Steps
- #820 for relevant issue
- Additional lore/lore-inspired names for all subcultures still needed before ill-fitting random character names can begin to be removed.
  - Exception: Blood elven culture has a glut and may require merges or removals to avoid file bloat.
- Localisation for added names may be needed.
- Next PR to add Satyr and Nightborne improvements.

### Changes
- Added WoW/RTS NPC names to High Elves, Blood Elves, Night Elves, Nighborne and Naga.
- Dynastic names with `"dynn_x"` point to historical dynasties described in `common/dynasties`. Additions without `"dynn_x"` are lore sourced but not described in 'common/dynasties`.
- Updated formatting in-line with #820 ; categories ordered by lore, lore-inspired (including from other subcultures), random generated.
- Pointed blood elf "dynn_x" defined in common\dynasties to blood elf culture and removed incorrect "dynn_" prefixes for high elven dynasties.
- Added missing dynn_Hawkspear, Brightsun, Salonar from bottom of Commonn\Dynasties to Blood Elf culture
- Replaced duplicate random dynasty names

```
Blackwing -> Dawnbreeze
Rosestrider -> Brightsong
Firebender -> Snowdawn
Phoenixwalker -> Daybreak
Bloodwood -> Bloodwrath
Dayreaver -> Daybreaker
Dayspear -> Dayblaze
Emberseeker -> Emberfall
Silvergaze -> Silversun
Stargaze -> Starsorrow
```

- Replaced thematically ineffective random dynasty names with lore names 

```
Flameflame -> Flameheart
Dewblade -> Dawnfury
Dewbringer -> Dawnstrike
Dewspear -> Dawnglaive
Heartheart -> Heartshade
Redseeker -> Redmorn (Blood Elf)
Redseeker -> Rosebreeze (High Elf)
Blackspell -> Brighthand (High Elf)
Blackspell -> Bloodblade (Blood Elf)
Blackfeather -> Bloodfire
Darkfury -> Dawnshield
Heartsprinter -> Morningsong
Coldbringer -> Ebonscorch
Coldheart -> Emberbinder
Coldshadow -> Brightstar
Downfall -> Sunhollow
Redbringer -> Riverwind (Blood Elf)
Redbringer -> Riverwind (High Elf)
Redforge -> Solarforge
Phoenixgaze -> Sunborn
Phoenixdown -> Truehair
Nightsworn -> Nightscorn
Colddown -> Cinderweave
Downflare -> Darkflare
Mirthsprinter -> Morrowsong
Mirthbinder -> Magehand
Downblade -> Everspring
Blackforge -> Lighthammer
Dewspell -> Dewspring
Downgaze -> Dawnrunner
Of the Nightfall -> Netherburn
Mirthflare -> Mourningsun
Darkdown -> Darkleaf
Autumnshade -> Springrunner
Coldwood -> Autumnwood
Morningbringer -> Morningstar
Moonbringer -> Moonvale (Blood Elf)
Moonbringer -> Loresong (High Elf)
Leafdown -> Feltouch
Leafblossom -> Dawnrose
Lightwood -> Lightblade
Heartwhisper -> Heartspear
Redbrook -> Roseblade
Leaflight -> Lightfall
Coldsworn -> Sunshadow
Nightsky -> Sunlance (High Elf)
Nightsky -> Azuresong (Blood Elf)
Morningshadow -> Sunshroud
Nightvale -> Belore
```

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
   - For all newly added first names, this error is returned:
   [21:25:45][culture_names.cpp:103]: Missing loc for name 'Allanah' in culture 'high_elf'
- [x] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
- Check if character and dynasty names from lore and lore-inspired categories appear when generating cultural names in the ruler designer. 
- Ensure no unintended text such as slashes or prefixes like "dynn_x" show up. 
- Review added character and dynasty names for suggestions especially regarding enduring character/dynasty names across subcultures.
   - Frequency can be turned

2022-01-10 11:39 UTC, zumbak04 requested changes

2022-01-10 11:39 UTC, zumbak04 commented on common/culture/cultures/elf.txt
> +			"dynn_Magehand"
Keep a few names on the same line.
Otherwise, it spams the file.

2022-01-17 15:57 UTC, zumbak04 commented on localization/english/dynasties/wc_dynasty_names_l_english.yml
> + dynn_Dawnbreeze:0 "Dawnbreeze"
New localization lines always should be at the end.

2022-01-17 15:57 UTC, zumbak04 commented on localization/english/dynasties/wc_dynasty_names_l_english.yml
> - dynn_Blackforge:0 "Blackforge"
If you remove the localization line, you should leave a gap.

2022-01-18 16:40 UTC, zumbak04 requested changes

2022-01-18 16:40 UTC, zumbak04 commented on common/culture/cultures/elf.txt
>  		color = rgb { 255 255 0 }
Error:
```
[20:38:29][culture_names.cpp:103]: Missing loc for name 'Tel'arn' in culture 'nightborne'
```

2022-02-06 02:53 UTC, IronyOwl approved these changes
High/Blood Elves look good, both dynasty names in common/dynasties and those not listed there were showing up.
Did get "Valandil" as a BE dynasty name, unsure if that's intended or a first name snuck in there.

Night Elf dynasty names look good, and had both historical and not.
Was getting a few weird first names, though. "Gedel" might be a NE name, but Luther, Hodle'mur, and Amywiar sound strange as male night elven first names.

Nightborne seemed okay, don't know enough about them to say much more. I wasn't able to get any historical dynastic names, but their dynastic namefile is small and doesn't list cultures so I assume that's intentional.

Satyr first names are very nicely thematic, I like those a lot. Dynastic names seemed good but I wasn't able to get any outside the dynasty file.
I did get one "dynn_Sargeron" as a dynasty name, however.

Naga first names were also very nice, and I got both historical and non from their dynasty names.
It seems like there's a bit of a gap between the historical and ahistorical ones, though. Almost all of the historical ones are two-part words (Hatecoil, Blackscale, Daggerspine), and almost all of the rest are slithery sounds separated by a ' (Naz'jar, Idra'kess, Vashj'elan). The ahistorical ones, by contrast, seem to be a mix of that latter category (Sral'ash, Shaz'jes, Grith'ja), and singular optionally slithery words (Sralar, Cithri).

2022-02-07 23:13 UTC, Loralius commented
>High/Blood Elves look good, both dynasty names in common/dynasties and those not listed there were showing up.
Did get "Valandil" as a BE dynasty name, unsure if that's intended or a first name snuck in there.

Everything here is intended. Names are drawn from 3 files for different purposes. The culture .txt contains all the first and dynasty names used during character creation and NPC generation. The dynasty .txt provides fixed dynasties for the characters in listed in history, and the characters listed in history are assigned fixed first names. Almost all minor/ahistorical characters in the history files are using generated (old) names which I have replaced and I hope to replace them in a future branch, at which point the player should only ever see names from the lists in the culture and dynasty .txt.

Valandril is a surname from this [RPG source](https://wowpedia.fandom.com/wiki/Ashra_Valandril).

> Night Elf dynasty names look good, and had both historical and not.
Was getting a few weird first names, though. "Gedel" might be a NE name, but Luther, Hodle'mur, and Amywiar sound strange as male night elven first names.

These are residual names from the old lists (currently in use on master). The Thalassian bias at Blizzard HQ is laid bare as that culture has as many named NPCs as the rest of the Elven group combined. Roughly a third of the name additions are my own  "lore-friendly" names in addition to named lore character names for most of the subcultures and still, they are not enough to completely throw out all of the old names (repetition is an issue) except for that of the Thalassian group. I intend to come back and add more "lore-friendly" names from time to time but for now I need to move onto the other culture groups. If anyone wishes to add their own suggestions, check the `elf.txt` in cultures and leave suggestions. 

> Nightborne

They are severely lacking in named lore characters so the ones I did add are probably being drowned out by the rest of the generated names. Apart from brainstorming more lore-inspired names, there is potential for some (but not too many) dynastic names from the other subcultures to be shared with the Nightborne, esp. Highborne and Thalassian, to reflect their shared heritage. Because they are not currently implemented, I expect they will receive a targeted cultural iteration once we introduce the Broken Isles.

> I did get one "dynn_Sargeron" as a dynasty name, however.

Great catch. I will fix this. Much appreciated :)

On Satyr and Naga, they are both in the unfortunate categories of being common hostile mobs in WoW and thus named characters are sparse. They will each require a more focused PR in the future.

2022-02-09 16:25 UTC, zumbak04 approved these changes
LGTM!
The code looks clean, didn't find any errors.

2022-02-09 17:22 UTC, merged