Special Buildings
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #865
Opened 2022-01-30 17:44 UTC by Gaben1025

## Changelog:
- Added new Special Buildings
    - Karazhan
    - Sunwell buildings
- Added the buildings to their respective provinces

2022-08-19 13:06 UTC, TheGroxEmpire reviewed
- The stats given to these special buildings aren't matching the values on the sheet:
- - Karazhan:
<details>

![image](https://user-images.githubusercontent.com/47816228/185621510-8a53d00a-5265-437a-9f98-88c0efddfdbd.png)
![image](https://user-images.githubusercontent.com/47816228/185621558-d4617759-547b-4b51-a1b5-85a453f9ece5.png)

</details>

- - Ruined Palace / Lordaeron Palace:
<details>

![image](https://user-images.githubusercontent.com/47816228/185623532-39064c71-a5da-4406-8d62-4c924e29b9e5.png)

![image](https://user-images.githubusercontent.com/47816228/185625254-4a8c407c-7b24-47f8-934d-7c46090046f5.png)
![image](https://user-images.githubusercontent.com/47816228/185625284-d24c307e-3b80-4d43-9765-7b29fd32f5ad.png)
</details>

- - Sunwell:
<details>

![image](https://user-images.githubusercontent.com/47816228/185624077-8d3b03de-1dbc-4a21-80b7-3a75c2c18da5.png)
![image](https://user-images.githubusercontent.com/47816228/185624205-613fa688-2279-4220-bb58-5fe43fe2a4ce.png)

</details>

- - Violet Citadel (Missing Garisson):
<details>

![image](https://user-images.githubusercontent.com/47816228/185624552-1603f4e4-00c1-4e7a-8e5b-142fdf88c99e.png)
![image](https://user-images.githubusercontent.com/47816228/185624650-4678d12a-384d-4568-9a2f-6f437945d713.png)

</details>

- I can't find Thoradin's wall in Arathi Highlands - Hillsbrad border

2022-08-21 15:54 UTC, TheGroxEmpire approved these changes
My concerns were fixed.

2022-08-21 19:50 UTC, ercarp requested changes
There are a few spelling errors that need to be fixed, but other than that it looks good. I included a few minor suggestions as well but you can take them or leave them.

2022-08-21 19:50 UTC, ercarp commented on localization/english/wc_buildings_l_english.yml
> + building_gurubashi_arena_01_desc:1 "The Gurubashi Arena provides ruffians a shot at competition, fame, and treasure. It is said that in ancient times, fights were to the death, and the sand of the a
```suggestion
 building_gurubashi_arena_01_desc:1 "The Gurubashi Arena provides ruffians a shot at competition, fame, and treasure. It is said that in ancient times, fights were to the death, and the sand of the arena was muddy with troll blood."
```

2022-08-21 19:50 UTC, ercarp commented on localization/english/wc_buildings_l_english.yml
> + building_type_karazhan_01_desc:1 "A massive tower that watches over Deadwind Pass. Its inhabitants wield magical powers coveted by all of Azeroth."
```suggestion
 building_type_karazhan_01_desc:1 "A massive tower that watches over Deadwind Pass. Its inhabitants wield magical powers coveted by every denizen of Azeroth."
```

I think it sounds fancier, but this is me being very pedantic.

2022-08-21 19:50 UTC, ercarp commented on localization/english/wc_buildings_l_english.yml
> + building_type_temple_of_atal_hakkar_01:0 "Temple of Atal'Hakar"
```suggestion
 building_type_temple_of_atal_hakkar_01:0 "Temple of Atal'Hakkar"
```

I believe it's spelled [with two k's](https://wowpedia.fandom.com/wiki/Temple_of_Atal%27Hakkar)?

2022-08-21 19:50 UTC, ercarp commented on localization/english/wc_buildings_l_english.yml
> + building_temple_of_atal_hakkar_01:1 "Temple of Atal'Hakar"
```suggestion
 building_temple_of_atal_hakkar_01:1 "Temple of Atal'Hakkar"
```

2022-08-21 19:50 UTC, ercarp commented on localization/english/wc_buildings_l_english.yml
> + building_type_thoradins_wall_01_desc:1 "Colossal walls that sheild the denzins of its holders domain. All unwanted guests must firstly face this almost insurmountable obstacle."
```suggestion
 building_type_thoradins_wall_01_desc:1 "Colossal walls that shield the denizens of its holder's domain. All unwanted guests must first face this almost insurmountable obstacle."
```

Spelling errors.

2022-08-21 19:50 UTC, ercarp commented on localization/english/wc_buildings_l_english.yml
> + building_thoradins_wall_01_desc:1 "Once a wonder for our people, a testament to our power and our technological prowess, Thoradin's Wall now only statnds as a symbol of our downfall. Some parts of t
```suggestion
 building_thoradins_wall_01_desc:1 "Once a wonder for our people, a testament to our power and our technological prowess, Thoradin's Wall now only stands as a symbol of our downfall. Some parts of the wall still remain and help keep the peace, but the mostly ruined wall is but a shell of the once great shield against those who would wish harm upon us."
```
Spelling error.

2022-08-21 19:50 UTC, ercarp commented on localization/english/wc_buildings_l_english.yml
> + building_ruined_palace_01_desc:1 "The Ruins of Lordaeron is all that remains of the city of Lordaeron, the great capital city of the Kingdom of Lordaeron. Now it serves as a sad reminder of the powe
```suggestion
 building_ruined_palace_01_desc:1 "The Ruins of Lordaeron is all that remains of the city of Lordaeron, the great capital city of the Kingdom of Lordaeron. Now it serves as a grim reminder of the power of the Scourge. The Ruined Palace still stands and its inhabitants are constantly haunted by the final tragic events that led to the death of King Terenas and the city's destruction."
```

I think grim sounds a bit better, but this is just a suggestion.

2022-08-21 19:50 UTC, ercarp commented on localization/english/wc_buildings_l_english.yml
> + building_type_sunwell_01_desc:1 "A fountain of mystical power located in the Sunwell Plateau on the Isle of Quel'Danas. Its presence in its users lives is comparable to eating or breathing."
```suggestion
 building_type_sunwell_01_desc:1 "A fountain of mystical power located within the Sunwell Plateau on the Isle of Quel'Danas. Its users rely on its energies for sustenance."
```

I think this part of the sentence sounded a bit confusing. Not sure if I made it better or worse though.

2022-08-21 19:50 UTC, ercarp commented on localization/english/wc_buildings_l_english.yml
> + building_sunwell_01_desc:1 "The Sunwell has empowered us high elves for roughly seven thousand years. Its presence in their our is comparable to eating or breathing. In the Sunwell's light, Quel'Tha
```suggestion
 building_sunwell_01_desc:1 "The Sunwell has empowered us high elves for roughly seven thousand years. Its presence in our lives is akin to eating or breathing. In the Sunwell's light, Quel'Thalas has grown mighty, becoming a beacon of power in the Eastern Kingdoms."
```
A grammar error and a small pedantic suggestion.

2022-08-21 19:50 UTC, ercarp commented on localization/english/wc_buildings_l_english.yml
> + building_type_violet_citadel_01_desc:1 "A Citadel working as both a place of study and progress as well as a bastion houseing great casters to defend against invading forces."
```suggestion
 building_type_violet_citadel_01_desc:1 "A Citadel working as both a place of study and progress as well as a bastion housing great casters to defend against invading forces."
```
Spelling error.

2022-08-21 19:50 UTC, ercarp commented on localization/english/wc_buildings_l_english.yml
> + building_violet_citadel_01_desc:1 "The Violet Citadel is the main fortress of Dalaran which houses the Chamber of Air, research laboratories and great spell libraries of the Kirin Tor."
```suggestion
 building_violet_citadel_01_desc:1 "The Violet Citadel is the main fortress of Dalaran which houses the Chamber of Air, research laboratories, and the great spell libraries of the Kirin Tor."
```

I would add an Oxford comma here for readability. 😄

2022-08-21 19:54 UTC, Gaben1025 reviewed
.

2022-08-21 19:58 UTC, ercarp approved these changes
On behalf of @Warcraft-GoA-Development-Team/english-proofreaders, localization looks good to me! Didn't review other areas of the PR.

2022-08-28 09:01 UTC, arithon requested changes
just a couple remarks that might be taken into consideration.

2022-08-28 16:18 UTC, arithon approved these changes

2022-08-29 18:38 UTC, zumbak04 commented on common/buildings/wc_special_buildings.txt
> +		caster_toughness_mult = 0.7
I would nerf it... looks too strong. Holy places give much less.

2022-08-29 21:29 UTC, Gaben1025 commented
<https://docs.google.com/spreadsheets/d/18zS-FAte6nsejx7rpzSmVuioRXps3iWSvSkx_xRJSWI/edit#gid=1906407470>

2022-09-04 20:28 UTC, zumbak04 commented on common/buildings/wc_special_buildings.txt
> +		caster_toughness_mult = 0.7
I would say other buildings need nerf too. If you use the balance spreedsheet, I should aim at lesser cost number.

2022-09-04 20:29 UTC, zumbak04 commented on common/buildings/wc_special_buildings.txt
> +		caster_toughness_mult = 0.7
40-30 prob.

2022-09-04 20:39 UTC, zumbak04 approved these changes
I'll hit approve, but left comments.

2023-01-07 04:14 UTC, merged