1.5.0 maa tasks
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #965
Opened 2022-11-08 03:33 UTC by Gaben1025

# MaA-Related Tasks
- [ ] Move starting MaAs from innovations to traditions
- [ ] Adapt `culture_has_skirmisher_maa`, `culture_has_archer_maa`, etc.
- [ ] Adapt new MaA types, `camel_cavalry` and `elephant_cavalry`
- [ ] `KnightCulture` should depend on language instead of culture group
- [ ] Use modifiers for mod MaA types in new modifiers
- [ ] Adapt `GetRegionalInfantryMAA`
- [ ] Adapt MaA types in `ep1_flavor.2000`

2022-11-08 03:48 UTC, Gaben1025 commented
@zumbak04 What exactly is left to be adapted?
![image](https://user-images.githubusercontent.com/74790101/200470682-6a4653e3-4979-4306-8f56-d7a3fde1894c.png)

2022-11-08 03:51 UTC, Gaben1025 commented
@zumbak04 Is this also done?
![image](https://user-images.githubusercontent.com/74790101/200471003-127db61e-bdbe-4529-9db4-acdee6ddff28.png)

![image](https://user-images.githubusercontent.com/74790101/200470983-f6a94442-a805-47b0-8b67-d78352b8593b.png)

2022-11-08 04:05 UTC, Gaben1025 commented
@zumbak04 Need elaboration on these 

![image](https://user-images.githubusercontent.com/74790101/200472683-9e820996-b77c-4c46-8686-c6819b8bfc7a.png)

2022-11-08 16:08 UTC, zumbak04 commented
> Use modifiers for mod MaA types in new modifiers

Most likely meant checking new modifiers (the ones in `common/modifiers`) and making sure they give bonuses to mod units along vanilla units).

> Adapt GetRegionalInfantryMAA, GetRegionalInfantryMAA, etc.

Should be pretty straigtforward. These are vanilla units and vanilla cultural parameters. Should be replaced by parameters from our cultural MaA traditions once we get them.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/200615438-a42bff58-9938-41f8-b823-2292f266c4e0.png)

</details>

> Adapt MaA types in ep1_flavor.2000

Vanilla leftovers. Should be adapted to our cultures and tested.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/200616141-80b0ee44-a2c9-430c-8ebc-1282a0243590.png)

</details>

2023-02-05 14:14 UTC, zumbak04 requested changes

2023-02-05 14:14 UTC, zumbak04 commented on events/dlc/ep1/ep1_flavor_events.txt
>  					OR = {
You missed a few parts in this file.
1. Set the flag, `flag:camel_cavalry`, etc. are set before. Our flags aren't.
![image](https://user-images.githubusercontent.com/46384992/216824337-d204f578-5212-4bdf-8460-61824f62479f.png)
2. A few usings of such flags in this file. Just seach for `flag:camel_cavalry` and do it by analogy.
![image](https://user-images.githubusercontent.com/46384992/216824405-fba33c20-6a5f-460d-be37-2fa9bb81198a.png)
3. `01_ep1_custom_loc.txt`, another file with `flag:camel_cavalry`. The same, do it by analogy.

2023-02-05 14:14 UTC, zumbak04 commented on localization/english/dlc/ep1/wc_dlc_ep1_flavor_events_l_english.yml
> + ep1_flavor.2000.archer_cavalry:0 ""The riders will train with running rabbits.""
Why they are copied? I don't see any changes.

2023-03-05 09:45 UTC, zumbak04 approved these changes
Hit approve, but pointed out one issue that needs to be addressed.

2023-03-05 09:45 UTC, zumbak04 commented on events/dlc/ep1/ep1_flavor_events.txt
> +
`ep1_flavor.2000`, in `immediate` block there.s a section that analyzes your army: which MaAs you have.
Check every use of `number_maa_regiments_of_base_type` in this file. There should be mod MaA checks nearby.

2023-03-05 10:51 UTC, arithon commented on localization/english/dlc/ep1/wc_dlc_ep1_flavor_events_l_english.yml
> + ep1_flavor.2000.massive_infantry:0 ""Our stoich giants will train their strength and grit.""
```suggestion
 ep1_flavor.2000.massive_infantry:0 ""Our stoic giants will train their strength and grit.""
```

2023-03-05 10:52 UTC, arithon commented on localization/english/dlc/ep1/wc_dlc_ep1_flavor_events_l_english.yml
> + ep1_flavor.2000.desc_caster:0 ""The casters are a versitile set of fighters, training them will keep our edge sharp as ever.""
```suggestion
 ep1_flavor.2000.desc_caster:0 ""The casters are a versatile set of fighters, training them will keep our edge sharp as ever.""
```

2023-03-05 10:53 UTC, arithon commented on localization/english/dlc/ep1/wc_dlc_ep1_flavor_events_l_english.yml
> + ep1_flavor.2000.desc_light_aerial:0 ""Control of every aspect of the battlefield is important, these riders will help is mantain control of the skies.""
```suggestion
 ep1_flavor.2000.desc_light_aerial:0 ""Control of every aspect of the battlefield is important, these riders will help us maintain control of the skies.""
```

2023-03-05 10:53 UTC, arithon commented on localization/english/dlc/ep1/wc_dlc_ep1_flavor_events_l_english.yml
> + ep1_flavor.2000.desc_massive_aerial:0 ""Death ffrom above must be guarenteed for our enemies; those providing should be evermore vigilant.""
```suggestion
 ep1_flavor.2000.desc_massive_aerial:0 ""Death from above must be guaranteed for our enemies; those providing should be evermore vigilant.""
```

2023-03-05 10:54 UTC, arithon commented on localization/english/dlc/ep1/wc_dlc_ep1_flavor_events_l_english.yml
> + ep1_flavor.2020.desc_knight_1_caster:0 ""...is that all you got magician? Well for my next trick, I will make you #EMP disappear#!!""
```suggestion
 ep1_flavor.2020.desc_knight_1_caster:0 ""...is that all you got, magician? Well for my next trick, I will make you #EMP disappear#!!""
```

2023-03-05 10:54 UTC, arithon commented on localization/english/dlc/ep1/wc_dlc_ep1_flavor_events_l_english.yml
> + ep1_flavor.2020.desc_knight_1_massive_aerial:0 ""...the bigger they are the harder they fall, especially from #EMP that height#!!"
```suggestion
 ep1_flavor.2020.desc_knight_1_massive_aerial:0 ""...the bigger they are, the harder they fall, especially from #EMP that height#!!"
```

2023-03-05 10:54 UTC, arithon commented on localization/english/dlc/ep1/wc_dlc_ep1_flavor_events_l_english.yml
> + ep1_flavor.2020.desc_knight_2_caster:0 ""Ha! Thats rich coming from a rag wearing clown. Go drink your little potions!""
```suggestion
 ep1_flavor.2020.desc_knight_2_caster:0 ""Ha! That's rich coming from a rag-wearing clown. Go drink your little potions!""
```

2023-03-05 10:56 UTC, arithon commented on localization/english/dlc/ep1/wc_dlc_ep1_flavor_events_l_english.yml
> + ep1_flavor.2020.desc_knight_2_light_aerial:0 ""Pah! You got your head in the clouds, or up somewhere else if we were to be honest!""
```suggestion
 ep1_flavor.2020.desc_knight_2_light_aerial:0 ""Pah! You got your head in the clouds or up somewhere else, if we were to be honest!""
```

2023-03-06 15:25 UTC, merged