Patreon characters
Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2 pull request #998
Opened 2023-01-07 16:05 UTC by Gaben1025

## Changelog:
- Added Patreon Charecters

Pulled from here:
https://docs.google.com/spreadsheets/d/1hKQmfMrI_d8FtRez5w68OfS1s0JVr5r2yF8nryGe104/edit#gid=1195489674

2023-01-12 05:53 UTC, TheDrPibb1999 requested changes
Ralanor Arnoldian is listed as a count on the document but is a courtier in game for all 3 starts. 
![Capture](https://user-images.githubusercontent.com/79172797/211988298-26b88008-59d7-4537-92dd-87321ab98e12.JPG)

2023-04-24 22:18 UTC, arithon requested changes
some localisation changes required.

2023-04-24 22:18 UTC, arithon commented on localization/german/dynasties/wc_dynasty_names_l_german.yml
> + dynn_Morarenko:0 "Morarenko"
why is morarenko in a different place in the german file than in english + french?

2023-04-24 22:18 UTC, arithon commented on localization/english/dynasties/wc_dynasty_names_l_english.yml
> + dynn_Mace_arosh:0 "Mace'arosh"
needs to be changed in german, too

2023-05-12 16:46 UTC, hamjustine commented
@TheGroxEmpire  Added Kireina Radiant Blade back and fixed missing dna for Aeraniel Silvermist

2023-06-03 16:28 UTC, arithon approved these changes
LGTM

2023-06-04 06:30 UTC, TheGroxEmpire approved these changes

2023-06-07 14:20 UTC, merged